export const FUNDING_SOURCE_TYPES = [
  "venture_capital",
  "angel",
  "corporate_venture",
  "family_office",
  "accelerator",
  "incubator",
  "founder_fellowship",
  "research_fellowship",
  "startup_competition",
  "innovation_prize",
  "government_grant",
  "private_grant",
  "research_grant",
  "startup_credit",
  "cloud_credit",
  "ai_credit",
  "student_program",
  "university_program",
  "strategic_partner",
  "customer_funded_pilot",
  "revenue_financing",
  "venture_debt",
  "bank_debt",
] as const;

export const FUNDING_OPPORTUNITY_STATES = [
  "DISCOVERED",
  "VERIFYING",
  "QUALIFYING",
  "QUALIFIED",
  "NOT_ELIGIBLE",
  "PREPARING",
  "READY",
  "WAITING_APPROVAL",
  "SUBMITTED",
  "INTERVIEW",
  "DILIGENCE",
  "OFFER",
  "REJECTED",
  "WITHDRAWN",
  "CLOSED",
  "REAPPLY",
] as const;

export const FUNDING_EVIDENCE_FIELDS = [
  "official_program_url",
  "provider_organization",
  "opportunity_type",
  "application_open_date",
  "deadline",
  "geography",
  "entity_requirements",
  "founder_requirements",
  "stage_requirements",
  "industry_requirements",
  "funding_amount",
  "equity_or_dilution",
  "fees",
  "use_of_funds_restrictions",
  "program_commitments",
  "data_sharing_requirements",
  "application_questions",
  "required_documents",
  "selection_process",
  "reapplication_policy",
  "source_observed_at",
] as const;

export const FUNDING_COMPANY_FACTS = [
  "founder_identity",
  "company_legal_name",
  "entity_status",
  "jurisdiction",
  "incorporation_date",
  "company_address",
  "website",
  "product_description",
  "problem",
  "solution",
  "target_customer",
  "market",
  "business_model",
  "pricing",
  "revenue",
  "paying_customers",
  "design_partners",
  "growth_metrics",
  "retention_metrics",
  "team",
  "founder_background",
  "technology",
  "ip",
  "traction_evidence",
  "funding_history",
  "cap_table",
  "cash",
  "runway",
  "fundraising_target",
  "use_of_funds",
  "banking_and_tax_documents",
] as const;

export const FUNDING_AUTONOMY_RULES = {
  auto: [
    "discover_public_opportunity",
    "verify_public_source",
    "extract_requirements",
    "check_non_sensitive_eligibility",
    "score_fit",
    "prepare_draft_answers",
    "prepare_deck_variant",
    "prepare_document_checklist",
    "update_funding_crm",
    "track_deadline",
  ],
  bounded: [
    "fill_non_binding_form_with_verified_facts",
    "schedule_meeting",
    "send_preapproved_routine_follow_up",
    "submit_preapproved_non_binding_program_application",
  ],
  founderApproval: [
    "material_financial_representation",
    "certification_or_attestation",
    "sensitive_diligence_disclosure",
    "change_fundraising_target",
    "change_equity_or_terms",
    "investor_outreach_to_sensitive_relationship",
    "exclusivity_or_rights",
    "grant_condition_with_material_obligation",
  ],
  neverAutonomous: [
    "sign_safe_or_term_sheet",
    "issue_equity",
    "change_cap_table",
    "accept_debt",
    "move_funds",
    "accept_binding_legal_terms",
    "misstate_traction_or_revenue",
    "hide_liabilities",
  ],
} as const;

export const CAPITAL_SUBSYSTEMS = [
  "Funding Radar",
  "Opportunity Verifier",
  "Eligibility Engine",
  "Fit & Expected-Value Scorer",
  "Deadline Calendar",
  "Founder/Company Verified Profile",
  "Claim Registry",
  "Application Answer Library",
  "Application Factory",
  "Deck Factory",
  "Financial Model",
  "Cap Table & Dilution Engine",
  "Investor Graph",
  "Warm Introduction Graph",
  "Investor CRM",
  "Meeting Preparation",
  "Objection Memory",
  "Data Room",
  "Diligence Agent",
  "Term Sheet Extractor/Comparator",
  "Round Strategy",
  "Credit Treasury",
  "Award/Restriction Tracker",
  "Reporting-Obligation Tracker",
  "Reapplication Calendar",
] as const;
