export const COMPANY_OS_RUNTIME_PLANES = [
  {
    id:"founder_surface",
    purpose:"Founder Command Center, Decision Room, approvals, briefs, exceptions and kill switches.",
    implementation:"Foremention Next.js app + authenticated APIs",
  },
  {
    id:"governance",
    purpose:"Constitution, policy, risk, budgets, reserved matters, approvals and action receipts.",
    implementation:"Foremention native + Supabase/RLS; OPA-style policy evaluation where useful",
  },
  {
    id:"orchestration",
    purpose:"24/7 events, schedules, retries, waits, concurrency, idempotency, compensation and DLQ.",
    implementation:"Inngest only durable orchestrator; AgentKit inside governed workflows",
  },
  {
    id:"company_truth",
    purpose:"Authoritative objectives, customers, agents, tasks, decisions, evidence, finance and company state.",
    implementation:"Supabase/Postgres + RLS",
  },
  {
    id:"temporal_memory",
    purpose:"Derived time-aware people/company/competitor/relationship history.",
    implementation:"Graphiti sidecar after evaluation; never authoritative over company truth",
  },
  {
    id:"procedural_memory",
    purpose:"Skills, SOPs, prompts, playbooks, workflows, ADRs and institutional learning.",
    implementation:"Git + Company OS registries + inspectable skill files",
  },
  {
    id:"secrets",
    purpose:"Raw credentials, OAuth secrets, generated passwords, signing keys and rotations.",
    implementation:"Dedicated secrets manager / Agent Vault-style proxy; secrets excluded from agent memory",
  },
  {
    id:"compute",
    purpose:"Model routing, fallbacks, quotas, credits, privacy and cost governance.",
    implementation:"Foremention Compute Governor + LiteLLM-style gateway; explicit provider adapters retained for product measurement",
  },
  {
    id:"tool_gateway",
    purpose:"Tool/MCP inventory, authenticated connectors, policy enforcement and action isolation.",
    implementation:"Foremention Tool/MCP Registry + native connectors; optional agentgateway/Composio behind policy",
  },
  {
    id:"engineering_sandbox",
    purpose:"Isolated coding, tests, patches, branches and PR creation.",
    implementation:"OpenHands/ephemeral Docker-style workspace; no direct production authority",
  },
  {
    id:"browser_workers",
    purpose:"Approved website interaction, portal forms, account setup and application workflows.",
    implementation:"Stagehand for repeatable flows; Browser Use for exploratory flows; domain/network restrictions",
  },
  {
    id:"research",
    purpose:"Search, crawl, documents, deep research and source verification.",
    implementation:"SearXNG + Crawl4AI + Docling + long-horizon research workers + Evidence Engine",
  },
  {
    id:"observability",
    purpose:"App errors, product analytics, workflow traces, model/tool traces, costs and evals.",
    implementation:"Sentry/OTel + PostHog + one selected AI-eval/trace platform",
  },
  {
    id:"communications",
    purpose:"Email, support, notifications, social and founder alerts.",
    implementation:"Existing outreach/email + Metricool + supported official connectors + notification layer",
  },
  {
    id:"artifact_storage",
    purpose:"Decks, applications, diligence, contracts, reports, exports and immutable evidence.",
    implementation:"Encrypted object storage with provenance and access controls",
  },
] as const;

export const COMPANY_OS_EVENT_PREFIXES = [
  "company",
  "objective",
  "task",
  "decision",
  "approval",
  "agent",
  "skill",
  "tool",
  "model",
  "budget",
  "security",
  "incident",
  "customer",
  "support",
  "product",
  "revenue",
  "sales",
  "outreach",
  "billing",
  "finance",
  "funding",
  "investor",
  "grant",
  "accelerator",
  "fellowship",
  "competition",
  "credit",
  "social",
  "media",
  "community",
  "partner",
  "competitor",
  "market",
  "technology",
  "repo",
  "vendor",
  "legal",
  "compliance",
  "people",
  "experiment",
  "deployment",
  "backup",
  "memory",
  "evidence",
] as const;

export const COMPANY_OS_EVENT_TYPES = [
  "company.stage.changed",
  "company.constraint.changed",
  "company.coverage_gap.detected",
  "objective.created",
  "objective.at_risk",
  "task.created",
  "task.blocked",
  "task.failed",
  "task.completed",
  "decision.required",
  "decision.approved",
  "decision.rejected",
  "approval.expiring",
  "agent.run.started",
  "agent.run.failed",
  "agent.eval.failed",
  "agent.autonomy.promoted",
  "agent.autonomy.demoted",
  "skill.discovered",
  "skill.quarantined",
  "skill.eval.passed",
  "skill.promoted",
  "tool.permission.denied",
  "model.quota.low",
  "model.provider.degraded",
  "budget.threshold.reached",
  "security.secret.exposed",
  "security.prompt_injection.detected",
  "security.tenant_boundary.violation",
  "incident.opened",
  "incident.contained",
  "incident.resolved",
  "customer.created",
  "customer.activation.stalled",
  "customer.activated",
  "customer.health.degraded",
  "customer.churn_risk.detected",
  "customer.expansion.detected",
  "customer.commitment.due",
  "support.ticket.received",
  "support.ticket.escalated",
  "product.feedback.received",
  "product.experiment.completed",
  "revenue.opportunity.created",
  "sales.meeting.booked",
  "sales.deal.stalled",
  "outreach.reply.received",
  "outreach.bounce.received",
  "outreach.complaint.received",
  "billing.payment.failed",
  "billing.invoice.overdue",
  "finance.runway.threshold",
  "finance.margin.degraded",
  "funding.opportunity.discovered",
  "funding.deadline.approaching",
  "funding.application.ready",
  "funding.application.submitted",
  "funding.application.result",
  "investor.reply.received",
  "investor.meeting.scheduled",
  "grant.certification.required",
  "accelerator.application.open",
  "fellowship.application.open",
  "competition.application.open",
  "credit.program.discovered",
  "credit.balance.low",
  "social.content.ready",
  "social.mention.detected",
  "media.opportunity.detected",
  "community.signal.detected",
  "partner.opportunity.detected",
  "competitor.change.detected",
  "market.signal.detected",
  "technology.signal.detected",
  "repo.security.advisory",
  "repo.capability.discovered",
  "vendor.renewal.approaching",
  "vendor.risk.changed",
  "legal.document.received",
  "compliance.requirement.changed",
  "people.hiring_trigger",
  "experiment.kill_threshold",
  "deployment.failed",
  "deployment.rolled_back",
  "backup.failed",
  "restore.test.failed",
  "memory.contradiction.detected",
  "evidence.stale",
] as const;

export const COMPANY_OS_GLOBAL_KILL_SWITCHES = [
  "STOP_ALL_AGENTS",
  "STOP_OUTBOUND",
  "STOP_EXTERNAL_WRITES",
  "STOP_DEPLOYS",
  "STOP_AI_SPEND",
  "STOP_BROWSER_AUTOMATION",
  "STOP_CUSTOMER_MUTATIONS",
  "STOP_BILLING_MUTATIONS",
  "STOP_CAPITAL_SUBMISSIONS",
] as const;

export const COMPANY_OS_TASK_STATES = [
  "PROPOSED",
  "QUEUED",
  "BLOCKED",
  "RUNNING",
  "WAITING_EXTERNAL",
  "WAITING_APPROVAL",
  "VERIFYING",
  "COMPLETED",
  "FAILED",
  "CANCELLED",
  "QUARANTINED",
] as const;

export const COMPANY_OS_AUTONOMY_STATES = [
  "PROPOSED",
  "SANDBOX",
  "SHADOW",
  "DRAFT",
  "APPROVAL",
  "BOUNDED_AUTO",
  "AUTO",
  "DEPRECATED",
  "RETIRED",
] as const;

export const COMPANY_OS_DATA_CLASSES = [
  "PUBLIC",
  "INTERNAL",
  "CONFIDENTIAL",
  "CUSTOMER_CONFIDENTIAL",
  "PII",
  "AUTH_SECRET",
  "PAYMENT",
  "SECURITY_SENSITIVE",
  "LEGAL_PRIVILEGED",
] as const;
