export type CompanySkillSpec = {
  id: string;
  category: string;
  risk: "read" | "internal_write" | "external_reversible" | "high_impact";
  purpose: string;
};

export const COMPANY_SKILL_SPECS: readonly CompanySkillSpec[] = [
  // Founder / governance / strategy
  {id:"objective-routing",category:"strategy",risk:"internal_write",purpose:"Map signals and work to approved objectives and owners."},
  {id:"constraint-analysis",category:"strategy",risk:"read",purpose:"Identify the dominant bottleneck to company progress."},
  {id:"decision-synthesis",category:"strategy",risk:"read",purpose:"Synthesize evidence, options, tradeoffs, reversibility and downside."},
  {id:"company-brief",category:"strategy",risk:"read",purpose:"Produce founder daily/weekly/monthly operating briefs."},
  {id:"strategy-analysis",category:"strategy",risk:"read",purpose:"Analyze company strategy, wedge, category, market and alternatives."},
  {id:"scenario-planning",category:"strategy",risk:"read",purpose:"Model competitive, market, regulatory, vendor and capital scenarios."},
  {id:"market-sizing",category:"strategy",risk:"read",purpose:"Maintain living TAM/SAM/SOM and category-expansion assumptions."},
  {id:"opportunity-cost",category:"strategy",risk:"read",purpose:"Compare competing uses of attention, cash and engineering capacity."},
  {id:"red-team",category:"strategy",risk:"read",purpose:"Attack assumptions and proposed actions with adversarial reasoning."},
  {id:"pre-mortem",category:"strategy",risk:"read",purpose:"Imagine failure before execution and identify preventions."},
  {id:"post-mortem",category:"strategy",risk:"internal_write",purpose:"Record causes, impact, lessons and corrective actions after failure."},
  {id:"assumption-challenge",category:"strategy",risk:"read",purpose:"Find disconfirming evidence for strategic assumptions."},
  {id:"capability-gap-analysis",category:"strategy",risk:"read",purpose:"Detect missing, obsolete, redundant or inferior company capabilities."},
  {id:"unknown-unknown-search",category:"strategy",risk:"read",purpose:"Search for important capabilities the company has not modeled yet."},

  // Product / design
  {id:"product-discovery",category:"product",risk:"read",purpose:"Discover customer problems, workflows and desired outcomes."},
  {id:"roadmap-prioritization",category:"product",risk:"internal_write",purpose:"Prioritize product work by customer value, evidence and strategic fit."},
  {id:"activation-analysis",category:"product",risk:"read",purpose:"Measure and diagnose activation and time-to-value."},
  {id:"retention-analysis",category:"product",risk:"read",purpose:"Analyze cohort return, retention and repeated decision value."},
  {id:"customer-research",category:"product",risk:"read",purpose:"Synthesize customer interviews, support, usage and market language."},
  {id:"buyer-question-research",category:"product",risk:"read",purpose:"Discover and validate recommendation/buyer questions."},
  {id:"voc-synthesis",category:"product",risk:"read",purpose:"Turn voice-of-customer evidence into themes and opportunities."},
  {id:"pricing-analysis",category:"product",risk:"read",purpose:"Analyze pricing, willingness-to-pay, packaging and competitive context."},
  {id:"packaging-analysis",category:"product",risk:"read",purpose:"Design and compare plans, limits, value metrics and enterprise packaging."},
  {id:"willingness-to-pay",category:"product",risk:"read",purpose:"Estimate and test buyer willingness-to-pay using evidence."},
  {id:"discount-analysis",category:"product",risk:"read",purpose:"Track discount leakage, objections and pricing power."},
  {id:"ux-research",category:"design",risk:"read",purpose:"Evaluate workflows, usability and user comprehension."},
  {id:"accessibility-review",category:"design",risk:"read",purpose:"Check accessibility requirements and regressions."},
  {id:"journey-mapping",category:"design",risk:"read",purpose:"Map end-to-end customer journeys and friction."},

  // Engineering
  {id:"architecture-rfc",category:"engineering",risk:"internal_write",purpose:"Create architecture proposals with alternatives, risks and migration plans."},
  {id:"repo-audit",category:"engineering",risk:"read",purpose:"Inspect repository structure, quality, security, duplication and debt."},
  {id:"implementation-plan",category:"engineering",risk:"internal_write",purpose:"Break approved work into bounded engineering tasks and dependencies."},
  {id:"release-risk",category:"engineering",risk:"read",purpose:"Assess release blast radius, dependencies and rollback readiness."},
  {id:"code-implementation",category:"engineering",risk:"internal_write",purpose:"Implement bounded code changes in isolated workspaces."},
  {id:"refactor",category:"engineering",risk:"internal_write",purpose:"Improve internal design without changing intended behavior."},
  {id:"test-generation",category:"engineering",risk:"internal_write",purpose:"Generate unit, integration, contract, E2E and regression tests."},
  {id:"dependency-upgrade",category:"engineering",risk:"internal_write",purpose:"Prepare tested dependency/security upgrades."},
  {id:"code-review",category:"engineering",risk:"read",purpose:"Independently review correctness, security, maintainability and scope."},
  {id:"architecture-review",category:"engineering",risk:"read",purpose:"Check implementation against ADRs, invariants and system boundaries."},
  {id:"regression-analysis",category:"engineering",risk:"read",purpose:"Detect likely regressions from code/schema/config changes."},
  {id:"test-design",category:"engineering",risk:"internal_write",purpose:"Design test matrices for normal, edge, abuse and failure paths."},
  {id:"browser-acceptance",category:"engineering",risk:"external_reversible",purpose:"Exercise signed-in product journeys in controlled environments."},
  {id:"regression-testing",category:"engineering",risk:"internal_write",purpose:"Run targeted and broad regression suites."},
  {id:"release-management",category:"engineering",risk:"high_impact",purpose:"Promote releases through staging, canary and production gates."},
  {id:"canary",category:"engineering",risk:"external_reversible",purpose:"Release to bounded traffic and evaluate health before expansion."},
  {id:"rollback",category:"engineering",risk:"high_impact",purpose:"Restore prior known-good state when safety thresholds fail."},
  {id:"release-evidence",category:"engineering",risk:"read",purpose:"Collect exact-SHA tests, security checks and deployment evidence."},
  {id:"migration-planning",category:"engineering",risk:"internal_write",purpose:"Plan schema/data migrations with compatibility and rollback."},
  {id:"schema-diff",category:"engineering",risk:"read",purpose:"Compare database/API schemas and identify breaking changes."},
  {id:"migration-verification",category:"engineering",risk:"external_reversible",purpose:"Validate migrations against isolated/restorable environments."},
  {id:"sbom",category:"engineering",risk:"read",purpose:"Generate and inspect software bills of materials."},
  {id:"vulnerability-triage",category:"engineering",risk:"read",purpose:"Assess vulnerability reachability, severity and remediation."},

  // SRE / operations
  {id:"sre-monitoring",category:"sre",risk:"read",purpose:"Monitor uptime, latency, saturation, errors and workflow health."},
  {id:"capacity-planning",category:"sre",risk:"read",purpose:"Forecast database, queue, compute, storage and support capacity."},
  {id:"queue-health",category:"sre",risk:"read",purpose:"Detect stuck jobs, backpressure, retries, DLQ growth and concurrency issues."},
  {id:"incident-triage",category:"sre",risk:"external_reversible",purpose:"Classify incidents and begin bounded containment."},
  {id:"incident-response",category:"sre",risk:"high_impact",purpose:"Coordinate containment, recovery, communication and evidence."},
  {id:"containment",category:"sre",risk:"high_impact",purpose:"Pause/revoke/isolate affected systems with reversible controls."},
  {id:"status-communication",category:"sre",risk:"external_reversible",purpose:"Prepare accurate internal/customer incident updates."},
  {id:"backup-audit",category:"sre",risk:"read",purpose:"Verify backup coverage, freshness, integrity and retention."},
  {id:"restore-test",category:"sre",risk:"external_reversible",purpose:"Exercise restores in isolated environments."},
  {id:"disaster-recovery",category:"sre",risk:"high_impact",purpose:"Execute approved recovery plans after major failure."},
  {id:"business-continuity",category:"sre",risk:"read",purpose:"Plan operating continuity under founder/provider/site outages."},

  // AI / data / evidence
  {id:"model-routing",category:"ai",risk:"internal_write",purpose:"Route tasks by quality, privacy, latency, availability and cost."},
  {id:"model-benchmark",category:"ai",risk:"read",purpose:"Benchmark models on Foremention golden datasets."},
  {id:"prompt-eval",category:"ai",risk:"read",purpose:"Evaluate prompts for quality, robustness and regressions."},
  {id:"provider-fallback",category:"ai",risk:"internal_write",purpose:"Select safe fallback providers when quotas/outages occur."},
  {id:"data-quality",category:"data",risk:"read",purpose:"Assess freshness, completeness, duplicates, grain and consistency."},
  {id:"schema-validation",category:"data",risk:"read",purpose:"Validate event/data contracts and reject malformed payloads."},
  {id:"lineage",category:"data",risk:"read",purpose:"Track where critical facts and metrics came from."},
  {id:"freshness-monitoring",category:"data",risk:"read",purpose:"Detect stale or outdated company intelligence."},
  {id:"source-evidence-verification",category:"evidence",risk:"read",purpose:"Verify claims against trustworthy primary or authoritative sources."},
  {id:"claim-grounding",category:"evidence",risk:"read",purpose:"Block unsupported external claims and distinguish inference from fact."},
  {id:"provenance",category:"evidence",risk:"read",purpose:"Record source, observed-at, transformation and confidence metadata."},
  {id:"web-research",category:"research",risk:"read",purpose:"Search current public information with traceable sources."},
  {id:"deep-research",category:"research",risk:"read",purpose:"Run multi-source, multi-step research with evidence synthesis."},
  {id:"document-ingestion",category:"research",risk:"read",purpose:"Parse PDFs/docs/spreadsheets/email/audio into structured evidence."},
  {id:"source-quality",category:"research",risk:"read",purpose:"Score source authority, recency, independence and relevance."},

  // Security / identity / secrets
  {id:"security-review",category:"security",risk:"read",purpose:"Review code, architecture and operations for security weaknesses."},
  {id:"threat-model",category:"security",risk:"read",purpose:"Model assets, adversaries, attack paths and mitigations."},
  {id:"agent-security",category:"security",risk:"read",purpose:"Assess excessive agency, prompt injection, poisoning and exfiltration."},
  {id:"enterprise-security",category:"security",risk:"read",purpose:"Prepare enterprise security posture and questionnaire evidence."},
  {id:"credential-request",category:"security",risk:"external_reversible",purpose:"Request scoped credential execution through a credential broker."},
  {id:"oauth-scope-review",category:"security",risk:"read",purpose:"Verify OAuth scopes are minimal and appropriate."},
  {id:"secret-rotation",category:"security",risk:"high_impact",purpose:"Rotate exposed/aged credentials under controlled procedures."},
  {id:"prompt-injection-scan",category:"security",risk:"read",purpose:"Detect malicious instructions in untrusted content/tool output."},
  {id:"mcp-security",category:"security",risk:"read",purpose:"Review MCP tools for permissions, exfiltration and supply-chain risk."},
  {id:"skill-security",category:"security",risk:"read",purpose:"Scan imported skills for malicious or over-privileged behavior."},
  {id:"exfiltration-test",category:"security",risk:"read",purpose:"Test whether agents/tools can leak secrets or restricted data."},
  {id:"abuse-detection",category:"security",risk:"read",purpose:"Detect suspicious users, API abuse and automated misuse."},
  {id:"fraud-triage",category:"security",risk:"external_reversible",purpose:"Classify suspected fraud and apply reversible controls."},
  {id:"rate-abuse",category:"security",risk:"external_reversible",purpose:"Detect and limit abusive traffic patterns."},
  {id:"account-risk",category:"security",risk:"read",purpose:"Score account compromise, fraud or abuse risk."},

  // Marketing / growth / distribution
  {id:"positioning",category:"marketing",risk:"read",purpose:"Develop and test clear differentiated positioning."},
  {id:"category-creation",category:"marketing",risk:"read",purpose:"Test category language and market understanding."},
  {id:"brand-strategy",category:"marketing",risk:"read",purpose:"Maintain coherent founder/corporate brand strategy."},
  {id:"content-strategy",category:"marketing",risk:"read",purpose:"Plan themes, audiences, channels and evidence-backed content."},
  {id:"linkedin-content",category:"marketing",risk:"external_reversible",purpose:"Create LinkedIn-native posts/documents."},
  {id:"instagram-content",category:"marketing",risk:"external_reversible",purpose:"Create Instagram-native posts/carousels/reels concepts."},
  {id:"facebook-content",category:"marketing",risk:"external_reversible",purpose:"Create Facebook-native company content."},
  {id:"x-content",category:"marketing",risk:"external_reversible",purpose:"Create X-native short-form content."},
  {id:"newsletter",category:"marketing",risk:"external_reversible",purpose:"Create evidence-backed newsletter content."},
  {id:"content-repurposing",category:"marketing",risk:"external_reversible",purpose:"Transform one insight into channel-native assets."},
  {id:"seo-research",category:"marketing",risk:"read",purpose:"Identify SEO demand, gaps and authority opportunities."},
  {id:"aeo-research",category:"marketing",risk:"read",purpose:"Identify AI/search recommendation visibility opportunities."},
  {id:"content-gap",category:"marketing",risk:"read",purpose:"Find missing topics versus buyers and competitors."},
  {id:"organic-opportunity",category:"marketing",risk:"read",purpose:"Prioritize organic distribution opportunities."},
  {id:"growth-experiment",category:"growth",risk:"external_reversible",purpose:"Run bounded acquisition/conversion experiments."},
  {id:"funnel-analysis",category:"growth",risk:"read",purpose:"Diagnose funnel drop-off and conversion quality."},
  {id:"free-tool-design",category:"growth",risk:"internal_write",purpose:"Design free tools that deliver value and attract qualified demand."},
  {id:"virality-analysis",category:"growth",risk:"read",purpose:"Evaluate collaboration/share loops that create product-led distribution."},
  {id:"distribution-strategy",category:"distribution",risk:"read",purpose:"Balance owned, earned, partner and rented channels."},
  {id:"relationship-graph",category:"distribution",risk:"internal_write",purpose:"Maintain people/organization relationships and next-best-actions."},
  {id:"channel-analysis",category:"distribution",risk:"read",purpose:"Analyze CAC, pipeline, retention and concentration by channel."},
  {id:"social-research",category:"distribution",risk:"read",purpose:"Research relevant social conversations and accounts."},
  {id:"social-scheduling",category:"distribution",risk:"external_reversible",purpose:"Schedule approved content through supported platforms."},
  {id:"brand-listening",category:"distribution",risk:"read",purpose:"Monitor brand, category, customer and competitor mentions."},
  {id:"media-research",category:"distribution",risk:"read",purpose:"Research journalists, outlets and current beats."},
  {id:"pr-pitch",category:"distribution",risk:"external_reversible",purpose:"Prepare targeted factual media pitches."},
  {id:"analyst-research",category:"distribution",risk:"read",purpose:"Research analysts and relevant market/category coverage."},
  {id:"crisis-comms",category:"distribution",risk:"high_impact",purpose:"Prepare controlled public communications during sensitive events."},
  {id:"podcast-research",category:"distribution",risk:"read",purpose:"Find relevant podcasts, hosts, audiences and guest paths."},
  {id:"event-research",category:"distribution",risk:"read",purpose:"Find conferences, webinars, meetups and CFPs."},
  {id:"cfp-application",category:"distribution",risk:"external_reversible",purpose:"Prepare and submit approved speaking proposals."},
  {id:"speaker-pitch",category:"distribution",risk:"external_reversible",purpose:"Prepare targeted speaker/guest outreach."},
  {id:"community-listening",category:"distribution",risk:"read",purpose:"Monitor relevant communities for buyer/market signals."},
  {id:"community-engagement",category:"distribution",risk:"external_reversible",purpose:"Participate helpfully in approved communities."},
  {id:"developer-relations",category:"distribution",risk:"external_reversible",purpose:"Support technical community, docs, demos and ecosystem adoption."},

  // Sales / revenue
  {id:"prospect-qualification",category:"sales",risk:"read",purpose:"Assess ICP fit, urgency, role, trigger and evidence."},
  {id:"account-research",category:"sales",risk:"read",purpose:"Research company, decision makers, competitors, triggers and context."},
  {id:"meeting-preparation",category:"sales",risk:"read",purpose:"Prepare discovery/demo agendas, hypotheses and questions."},
  {id:"pilot-design",category:"sales",risk:"internal_write",purpose:"Design measurable scoped pilots with success criteria."},
  {id:"deal-strategy",category:"sales",risk:"read",purpose:"Identify obstacles, stakeholders, risks and next best actions."},
  {id:"lead-discovery",category:"sales",risk:"read",purpose:"Discover potential accounts and decision makers from approved sources."},
  {id:"buyer-research",category:"sales",risk:"read",purpose:"Research buyer priorities and evidence before outreach."},
  {id:"mini-audit",category:"sales",risk:"read",purpose:"Generate evidence-backed Foremention mini-audits for qualified prospects."},
  {id:"sales-email",category:"sales",risk:"external_reversible",purpose:"Draft/send policy-compliant personalized outbound."},
  {id:"follow-up",category:"sales",risk:"external_reversible",purpose:"Generate context-aware follow-up based on previous interaction."},
  {id:"reply-classification",category:"sales",risk:"read",purpose:"Classify positive, objection, referral, unsubscribe, bounce and other replies."},
  {id:"deal-desk",category:"sales",risk:"high_impact",purpose:"Coordinate commercial, legal, security and pricing exceptions."},
  {id:"discount-policy",category:"sales",risk:"high_impact",purpose:"Apply approved discount authority and escalate exceptions."},
  {id:"security-questionnaire",category:"sales",risk:"external_reversible",purpose:"Prepare evidence-backed enterprise security responses."},
  {id:"contract-triage",category:"sales",risk:"high_impact",purpose:"Identify commercial/legal issues requiring review."},
  {id:"crm-hygiene",category:"revops",risk:"internal_write",purpose:"Maintain accurate accounts, contacts, opportunities and activities."},
  {id:"pipeline-analysis",category:"revops",risk:"read",purpose:"Analyze stage health, conversion and stalled opportunities."},
  {id:"forecasting",category:"revops",risk:"read",purpose:"Generate evidence-based forecasts without fabricating certainty."},
  {id:"attribution",category:"revops",risk:"read",purpose:"Blend self-reported, CRM, social, referral and web attribution."},
  {id:"sender-health",category:"revops",risk:"read",purpose:"Monitor domain/mailbox sending health and capacity."},
  {id:"deliverability",category:"revops",risk:"external_reversible",purpose:"Monitor and optimize compliant email deliverability."},
  {id:"dns-authentication",category:"revops",risk:"external_reversible",purpose:"Audit SPF, DKIM and DMARC configuration."},
  {id:"bounce-analysis",category:"revops",risk:"read",purpose:"Classify bounces and invalidate unsafe addresses."},
  {id:"suppression",category:"revops",risk:"internal_write",purpose:"Enforce unsubscribe, complaint and invalid-address suppression."},

  // Customer
  {id:"customer-success",category:"customer",risk:"external_reversible",purpose:"Drive measurable customer outcomes and proactive guidance."},
  {id:"health-scoring",category:"customer",risk:"read",purpose:"Assess customer health from activation, usage, support and outcomes."},
  {id:"churn-risk",category:"customer",risk:"read",purpose:"Identify and explain churn/renewal risk."},
  {id:"expansion-opportunity",category:"customer",risk:"read",purpose:"Identify justified expansion opportunities based on value."},
  {id:"support-response",category:"customer",risk:"external_reversible",purpose:"Respond to routine support with evidence and policy."},
  {id:"issue-classification",category:"customer",risk:"read",purpose:"Classify support severity, ownership and escalation."},
  {id:"knowledge-retrieval",category:"customer",risk:"read",purpose:"Retrieve product/company knowledge relevant to support."},
  {id:"escalation",category:"customer",risk:"internal_write",purpose:"Route sensitive/blocked issues to appropriate authority."},
  {id:"onboarding",category:"customer",risk:"external_reversible",purpose:"Guide customer setup and workflow configuration."},
  {id:"activation",category:"customer",risk:"external_reversible",purpose:"Drive first completed value cycle."},
  {id:"customer-education",category:"customer",risk:"external_reversible",purpose:"Create training and best-practice guidance."},
  {id:"customer-advocacy",category:"customer",risk:"external_reversible",purpose:"Identify and request approved advocacy opportunities."},
  {id:"case-study",category:"customer",risk:"external_reversible",purpose:"Develop evidence-backed case studies with permission."},
  {id:"referral",category:"customer",risk:"external_reversible",purpose:"Request/refine referrals where customer outcomes justify it."},
  {id:"referenceability",category:"customer",risk:"read",purpose:"Track which customers can serve as references."},

  // Partnerships
  {id:"partnership-research",category:"partnerships",risk:"read",purpose:"Find strategic, technology, channel and ecosystem partners."},
  {id:"partner-fit",category:"partnerships",risk:"read",purpose:"Assess strategic and economic partner fit."},
  {id:"partner-economics",category:"partnerships",risk:"read",purpose:"Model referral/reseller/marketplace economics and conflicts."},
  {id:"co-marketing",category:"partnerships",risk:"external_reversible",purpose:"Plan joint content, webinars, launches and customer programs."},

  // Capital / funding
  {id:"funding-strategy",category:"capital",risk:"read",purpose:"Define capital needs, sources, timing and non-dilutive/equity mix."},
  {id:"funding-radar",category:"capital",risk:"read",purpose:"Continuously find investors, accelerators, grants, fellowships, competitions and credits."},
  {id:"capital-prioritization",category:"capital",risk:"read",purpose:"Rank capital opportunities by fit, expected value, dilution, time and restrictions."},
  {id:"application-portfolio",category:"capital",risk:"internal_write",purpose:"Track all funding applications and next actions."},
  {id:"investor-research",category:"capital",risk:"read",purpose:"Research investor thesis, check size, stage, geography, partners and portfolio."},
  {id:"investor-fit",category:"capital",risk:"read",purpose:"Score investor fit without predicting or fabricating interest."},
  {id:"warm-intro-path",category:"capital",risk:"read",purpose:"Find lawful relationship paths and mutual connections."},
  {id:"accelerator-discovery",category:"capital",risk:"read",purpose:"Find currently open accelerator/incubator programs."},
  {id:"accelerator-eligibility",category:"capital",risk:"read",purpose:"Check objective eligibility requirements and restrictions."},
  {id:"accelerator-application",category:"capital",risk:"external_reversible",purpose:"Prepare/submit approved non-binding accelerator applications."},
  {id:"fellowship-discovery",category:"capital",risk:"read",purpose:"Find founder, student, research and innovation fellowships."},
  {id:"fellowship-eligibility",category:"capital",risk:"read",purpose:"Check fellowship criteria, dates and commitments."},
  {id:"fellowship-application",category:"capital",risk:"external_reversible",purpose:"Prepare/submit approved fellowship applications."},
  {id:"grant-discovery",category:"capital",risk:"read",purpose:"Find public/private/non-dilutive grants."},
  {id:"grant-eligibility",category:"capital",risk:"read",purpose:"Check geography, entity, technology, stage and use-of-funds requirements."},
  {id:"grant-application",category:"capital",risk:"external_reversible",purpose:"Prepare grant application content and evidence."},
  {id:"certification-gate",category:"capital",risk:"high_impact",purpose:"Escalate certifications, attestations and binding representations."},
  {id:"competition-discovery",category:"capital",risk:"read",purpose:"Find startup/pitch/innovation competitions."},
  {id:"competition-application",category:"capital",risk:"external_reversible",purpose:"Prepare competition submissions."},
  {id:"pitch-submission",category:"capital",risk:"external_reversible",purpose:"Prepare pitch scripts, forms and required materials."},
  {id:"startup-credit-discovery",category:"capital",risk:"read",purpose:"Find cloud, AI, developer, startup, student and partner credit programs."},
  {id:"credit-eligibility",category:"capital",risk:"read",purpose:"Check credit-program eligibility and restrictions."},
  {id:"credit-application",category:"capital",risk:"external_reversible",purpose:"Prepare and submit approved credit applications."},
  {id:"credit-optimization",category:"capital",risk:"internal_write",purpose:"Route approved workloads to credits/free tiers before cash."},
  {id:"application-form-fill",category:"capital",risk:"external_reversible",purpose:"Fill approved application portals using verified company facts."},
  {id:"application-answer-library",category:"capital",risk:"internal_write",purpose:"Maintain reusable verified answers with evidence and freshness."},
  {id:"document-packaging",category:"capital",risk:"internal_write",purpose:"Assemble required application/diligence documents."},
  {id:"fact-check",category:"capital",risk:"read",purpose:"Block unsupported traction, revenue, legal or team claims."},
  {id:"pitch-deck",category:"capital",risk:"external_reversible",purpose:"Create and maintain evidence-backed pitch decks."},
  {id:"narrative",category:"capital",risk:"read",purpose:"Maintain coherent company/fundraising narrative without hype fabrication."},
  {id:"traction-evidence",category:"capital",risk:"read",purpose:"Bind traction claims to authoritative records."},
  {id:"fundraising-outreach",category:"capital",risk:"external_reversible",purpose:"Prepare/send approved investor outreach from trusted mailboxes."},
  {id:"warm-intro-request",category:"capital",risk:"external_reversible",purpose:"Draft targeted introduction requests to mutual contacts."},
  {id:"investor-follow-up",category:"capital",risk:"external_reversible",purpose:"Maintain context-aware investor follow-up."},
  {id:"investor-crm",category:"capital",risk:"internal_write",purpose:"Maintain investor stages, interactions, fit and next actions."},
  {id:"investor-update",category:"capital",risk:"external_reversible",purpose:"Prepare periodic factual investor updates."},
  {id:"data-room",category:"capital",risk:"external_reversible",purpose:"Maintain diligence document inventory, permissions and freshness."},
  {id:"diligence",category:"capital",risk:"read",purpose:"Answer diligence from authoritative sources without guessing."},
  {id:"cap-table",category:"capital",risk:"high_impact",purpose:"Calculate current and scenario ownership deterministically."},
  {id:"safe-dilution-analysis",category:"capital",risk:"high_impact",purpose:"Model SAFE dilution and conversion scenarios."},
  {id:"option-pool",category:"capital",risk:"high_impact",purpose:"Model option-pool creation/refresh and dilution."},
  {id:"priced-round",category:"capital",risk:"high_impact",purpose:"Model priced-round ownership and proceeds."},
  {id:"financial-model",category:"capital",risk:"internal_write",purpose:"Build conservative/base/upside operating models."},
  {id:"scenario-finance",category:"capital",risk:"read",purpose:"Stress-test fundraising, growth and runway assumptions."},
  {id:"runway-analysis",category:"capital",risk:"read",purpose:"Calculate cash runway under explicit assumptions."},

  // Finance
  {id:"saas-metrics",category:"finance",risk:"read",purpose:"Calculate MRR/ARR, GRR, NRR, churn, expansion and related metrics."},
  {id:"unit-economics",category:"finance",risk:"read",purpose:"Calculate CAC, LTV, payback, contribution margin and segment economics."},
  {id:"revenue-quality",category:"finance",risk:"read",purpose:"Separate recurring, services, pilots, discounts and one-time revenue."},
  {id:"gross-margin",category:"finance",risk:"read",purpose:"Attribute compute, search, data, support and infrastructure cost to revenue."},
  {id:"cash-runway",category:"finance",risk:"read",purpose:"Monitor cash, burn and runway."},
  {id:"treasury-monitoring",category:"finance",risk:"read",purpose:"Monitor cash concentration and treasury policy."},
  {id:"fx-risk",category:"finance",risk:"read",purpose:"Monitor material currency exposure."},
  {id:"counterparty-risk",category:"finance",risk:"read",purpose:"Track bank/payment/vendor concentration."},
  {id:"usage-metering",category:"finance",risk:"internal_write",purpose:"Measure billable usage and cost drivers."},
  {id:"billing",category:"finance",risk:"external_reversible",purpose:"Create/manage approved subscriptions, invoices and billing state."},
  {id:"entitlements",category:"finance",risk:"internal_write",purpose:"Enforce plan/product access consistently."},
  {id:"collections",category:"finance",risk:"external_reversible",purpose:"Track and follow up on receivables under policy."},
  {id:"invoice-fraud",category:"finance",risk:"read",purpose:"Detect anomalous invoices and payment instructions."},
  {id:"vendor-fraud",category:"finance",risk:"read",purpose:"Detect suspicious vendor changes and requests."},
  {id:"payment-anomaly",category:"finance",risk:"read",purpose:"Detect unusual payment/refund patterns."},

  // Legal / compliance / people / vendors
  {id:"legal-document-triage",category:"legal",risk:"read",purpose:"Classify legal documents and identify issues needing counsel/founder."},
  {id:"contract-review-assist",category:"legal",risk:"high_impact",purpose:"Extract and compare contract terms; never independently provide binding legal approval."},
  {id:"privacy-review",category:"legal",risk:"read",purpose:"Assess data handling against company privacy obligations."},
  {id:"ip-tracking",category:"legal",risk:"internal_write",purpose:"Track trademarks, code/data rights, licenses and trade-secret controls."},
  {id:"regulatory-intelligence",category:"compliance",risk:"read",purpose:"Monitor relevant regulatory changes."},
  {id:"compliance-mapping",category:"compliance",risk:"read",purpose:"Map obligations to controls and evidence."},
  {id:"control-gap",category:"compliance",risk:"read",purpose:"Identify missing or ineffective controls."},
  {id:"control-testing",category:"audit",risk:"read",purpose:"Test operational/security/financial controls."},
  {id:"audit-evidence",category:"audit",risk:"read",purpose:"Collect inspectable evidence for controls and decisions."},
  {id:"segregation-review",category:"audit",risk:"read",purpose:"Detect conflicts where proposer/reviewer/deployer are improperly combined."},
  {id:"policy-audit",category:"audit",risk:"read",purpose:"Verify actual actions comply with configured policies."},
  {id:"insurance-gap",category:"risk",risk:"read",purpose:"Identify missing stage-appropriate insurance coverage."},
  {id:"coverage-review",category:"risk",risk:"read",purpose:"Review policy limits/exclusions with expert escalation."},
  {id:"talent-radar",category:"people",risk:"read",purpose:"Build relationships with future high-leverage hires/advisors."},
  {id:"hiring-trigger",category:"people",risk:"read",purpose:"Determine when human talent creates more leverage than automation/contracting."},
  {id:"candidate-research",category:"people",risk:"read",purpose:"Research candidate experience from authorized/public sources."},
  {id:"people-ops",category:"people",risk:"internal_write",purpose:"Manage approved people-process workflows."},
  {id:"compensation",category:"people",risk:"high_impact",purpose:"Prepare compensation analysis and proposals."},
  {id:"employee-equity",category:"people",risk:"high_impact",purpose:"Prepare equity grant/option-pool analysis."},
  {id:"succession",category:"people",risk:"high_impact",purpose:"Maintain key-person and leadership continuity plans."},
  {id:"vendor-due-diligence",category:"vendor",risk:"read",purpose:"Assess vendor security, privacy, legal, technical and financial risk."},
  {id:"vendor-comparison",category:"vendor",risk:"read",purpose:"Compare vendors on TCO, quality, lock-in and risk."},
  {id:"renewal-analysis",category:"vendor",risk:"read",purpose:"Evaluate renewals and alternatives."},
  {id:"vendor-exit",category:"vendor",risk:"external_reversible",purpose:"Plan/test provider migration and continuity."},
  {id:"ma-screening",category:"corpdev",risk:"read",purpose:"Screen acquisition/partnership targets."},
  {id:"build-buy-partner",category:"corpdev",risk:"read",purpose:"Compare build, buy, integrate and partner options."},
  {id:"international-expansion",category:"corpdev",risk:"high_impact",purpose:"Assess market/entity/tax/legal/GT M readiness for new countries."},
  {id:"strategic-alternatives",category:"corpdev",risk:"read",purpose:"Maintain fundraising/profitability/M&A/platform optionality."},

  // Intelligence / resources / evolution / enterprise value
  {id:"world-radar",category:"intelligence",risk:"read",purpose:"Monitor relevant market/company/technology/regulatory signals."},
  {id:"competitor-analysis",category:"intelligence",risk:"read",purpose:"Maintain dated competitor facts, capabilities and changes."},
  {id:"technology-radar",category:"intelligence",risk:"read",purpose:"Monitor models, APIs, frameworks and architecture changes."},
  {id:"signal-verification",category:"intelligence",risk:"read",purpose:"Verify signal authenticity, date, scope and importance."},
  {id:"proven-playbook",category:"intelligence",risk:"read",purpose:"Extract context-aware operating patterns from strong companies."},
  {id:"failure-library",category:"intelligence",risk:"internal_write",purpose:"Capture failure patterns and prevention lessons."},
  {id:"cross-company-pattern",category:"intelligence",risk:"read",purpose:"Compare practices across multiple companies before adapting."},
  {id:"resource-hunting",category:"resource",risk:"read",purpose:"Find free tiers, credits, APIs, programs and tools."},
  {id:"oss-evaluation",category:"resource",risk:"read",purpose:"Evaluate OSS maturity, license, security, fit and TCO."},
  {id:"api-evaluation",category:"resource",risk:"read",purpose:"Evaluate external APIs for quality, limits, privacy and cost."},
  {id:"quota-routing",category:"resource",risk:"internal_write",purpose:"Route work across remaining provider quotas."},
  {id:"cost-routing",category:"resource",risk:"internal_write",purpose:"Choose cheapest acceptable provider."},
  {id:"provider-health",category:"resource",risk:"read",purpose:"Monitor provider latency, errors and availability."},
  {id:"github-research",category:"resource",risk:"read",purpose:"Discover relevant GitHub repositories and inspect source/maturity."},
  {id:"license-review",category:"resource",risk:"read",purpose:"Check software/content licenses and commercial constraints."},
  {id:"supply-chain-review",category:"resource",risk:"read",purpose:"Assess dependencies, maintainers, provenance and build risks."},
  {id:"workflow-capture",category:"service_to_software",risk:"internal_write",purpose:"Capture repeated manual customer workflows."},
  {id:"productization-detector",category:"service_to_software",risk:"read",purpose:"Detect repeated valuable service work suitable for software."},
  {id:"manual-to-auto",category:"service_to_software",risk:"internal_write",purpose:"Move repeatable work through human→AI draft→bounded auto→feature."},
  {id:"customer-language-learning",category:"service_to_software",risk:"internal_write",purpose:"Preserve customer language and objections for product learning."},
  {id:"agent-evaluation",category:"evolution",risk:"read",purpose:"Evaluate task quality, reliability, cost and safety."},
  {id:"agent-improvement",category:"evolution",risk:"internal_write",purpose:"Propose improved prompts, tools, routing or decomposition."},
  {id:"skill-generation",category:"evolution",risk:"internal_write",purpose:"Convert repeated successful procedures into inspectable proposed skills."},
  {id:"architecture-improvement",category:"evolution",risk:"internal_write",purpose:"Propose refactors/removals when complexity exceeds value."},
  {id:"drift-detection",category:"evolution",risk:"read",purpose:"Detect declining agent/model/workflow performance."},
  {id:"promotion-review",category:"evolution",risk:"internal_write",purpose:"Promote capabilities after evidence thresholds are met."},
  {id:"demotion-review",category:"evolution",risk:"internal_write",purpose:"Reduce autonomy when quality/safety degrades."},
  {id:"pmf-evidence",category:"enterprise_value",risk:"read",purpose:"Assess activation, retention, willingness-to-pay, references and pull."},
  {id:"moat-analysis",category:"enterprise_value",risk:"read",purpose:"Assess data, workflow, brand, ecosystem and distribution defensibility."},
  {id:"scale-readiness",category:"enterprise_value",risk:"read",purpose:"Gate scaling on product/support/margins/infrastructure/retention/GTM readiness."},
  {id:"billion-dollar-scoreboard",category:"enterprise_value",risk:"read",purpose:"Track durable enterprise-value drivers rather than valuation theater."},
] as const;

export const COMPANY_SKILL_IDS = COMPANY_SKILL_SPECS.map((skill) => skill.id);
