export type CompanyWorkflowSpec = {
  id: string;
  ownerAgent: string;
  trigger: string;
  steps: readonly string[];
  consequence: "read" | "internal" | "external" | "high_impact";
};

export const COMPANY_WORKFLOWS: readonly CompanyWorkflowSpec[] = [
  {id:"company_constraint_loop",ownerAgent:"chief_of_staff",trigger:"daily + material company event",consequence:"internal",steps:["compile company state","score constraints","challenge with contrarian agent","select dominant constraint","allocate bounded work","measure","repeat"]},
  {id:"founder_decision_rounds",ownerAgent:"chief_of_staff",trigger:"D3/high-impact decision",consequence:"high_impact",steps:["signal","independent facts","department opinions","red team","options including do nothing","founder decision packet","execution","outcome review","institutional learning"]},
  {id:"customer_activation_loop",ownerAgent:"onboarding_agent",trigger:"new design partner/customer",consequence:"external",steps:["setup","five questions","competitors","live run","Source X-Ray review","decision-relevant insight","commitment capture","health baseline"]},
  {id:"customer_risk_loop",ownerAgent:"customer_success_brain",trigger:"customer.health.degraded",consequence:"external",steps:["load goals/history","diagnose cause","prepare intervention","policy check","contact if allowed","measure outcome","update health"]},
  {id:"customer_advocacy_loop",ownerAgent:"advocacy_agent",trigger:"verified customer outcome",consequence:"external",steps:["verify outcome","check permission/readiness","select case study/referral/reference path","request approval/permission","publish or record result"]},
  {id:"prospect_to_meeting",ownerAgent:"sales_brain",trigger:"qualified account signal",consequence:"external",steps:["account research","buyer research","evidence-backed mini-audit","message draft","sender/suppression check","send if policy allows","classify reply","meeting handoff"]},
  {id:"reply_to_pipeline",ownerAgent:"revops_agent",trigger:"outreach.reply.received",consequence:"internal",steps:["classify reply","update account/contact/opportunity","schedule follow-up or suppress","surface objections","feed customer/market learning"]},
  {id:"funding_radar_loop",ownerAgent:"capital_brain",trigger:"daily + public funding signal",consequence:"internal",steps:["discover opportunities","verify official source","classify type","eligibility check","fit/value score","deadline tracking","create funding record","route to specialist agent"]},
  {id:"accelerator_application",ownerAgent:"accelerator_agent",trigger:"qualified accelerator",consequence:"external",steps:["verify eligibility","load verified company profile","assemble answers","fact check","collect documents","browser/API fill","certification check","submit if authorized","follow-up"]},
  {id:"grant_application",ownerAgent:"grant_agent",trigger:"qualified grant",consequence:"high_impact",steps:["verify program authority","eligibility","use-of-funds fit","answer/evidence pack","budget narrative","document pack","certification gate","founder approval if required","submission","reporting obligations tracking"]},
  {id:"fellowship_application",ownerAgent:"fellowship_agent",trigger:"qualified fellowship",consequence:"external",steps:["verify founder eligibility","program fit","answer library","personal/company narrative","document pack","submit if authorized","follow-up"]},
  {id:"competition_application",ownerAgent:"competition_agent",trigger:"qualified competition",consequence:"external",steps:["verify rules","pitch variant","application","deck/video/script requirements","submit if authorized","calendar next round"]},
  {id:"startup_credit_application",ownerAgent:"startup_credit_agent",trigger:"qualified credit program",consequence:"external",steps:["eligibility","current credits check","required entity/account setup","application","track award/expiry","route workloads to awarded credits"]},
  {id:"investor_outreach_loop",ownerAgent:"fundraising_outreach_agent",trigger:"approved investor target",consequence:"external",steps:["investor thesis check","conflict/portfolio check","warm path check","founder-quality message","approval if required","send from trusted mailbox","follow-up","CRM update"]},
  {id:"investor_diligence_loop",ownerAgent:"ir_agent",trigger:"investor diligence request",consequence:"high_impact",steps:["classify request","retrieve authoritative evidence","flag sensitive fields","prepare response","founder/legal approval where needed","share through data room","audit access"]},
  {id:"resource_hunter_loop",ownerAgent:"resource_hunter_agent",trigger:"weekly + spend/quota signal",consequence:"internal",steps:["scan credits/free tiers/models/APIs/OSS","verify terms","estimate TCO/quality/privacy","recommend build-buy-integrate","apply or trial under policy","update credit treasury"]},
  {id:"oss_quarantine_pipeline",ownerAgent:"oss_radar_agent",trigger:"repo.capability.discovered",consequence:"internal",steps:["license","maintainer/activity","OpenSSF/provenance","SBOM","vulnerability/secret scan","prompt/MCP security","sandbox","benchmark","decision: integrate/reference/reject"]},
  {id:"engineering_change_pipeline",ownerAgent:"engineering_brain",trigger:"approved engineering task",consequence:"internal",steps:["RFC/plan if needed","ephemeral workspace","branch","implementation","tests","security scans","independent review","PR","CI","approval gate","staging"]},
  {id:"release_pipeline",ownerAgent:"release_agent",trigger:"approved green release candidate",consequence:"high_impact",steps:["exact SHA evidence","migration/rollback readiness","staging","smoke","canary","health gates","production approval","deploy","observe","rollback if thresholds fail"]},
  {id:"security_incident_loop",ownerAgent:"incident_commander",trigger:"security incident signal",consequence:"high_impact",steps:["verify signal","contain reversibly","preserve evidence","classify severity","rotate/revoke if needed","customer/legal comms gate","recover","RCA","control improvements"]},
  {id:"social_content_loop",ownerAgent:"distribution_brain",trigger:"verified market/company insight",consequence:"external",steps:["canonical insight","claim/evidence check","channel-native variants","brand review","schedule/publish if authorized","measure","learn"]},
  {id:"media_opportunity_loop",ownerAgent:"media_pr_agent",trigger:"relevant journalist/analyst/media signal",consequence:"external",steps:["research person/outlet","fit","recent work","relationship path","pitch draft","claim review","approval if sensitive","send","track"]},
  {id:"world_radar_loop",ownerAgent:"world_radar_agent",trigger:"continuous scheduled research",consequence:"internal",steps:["search","retrieve","verify source/date","classify competitor/market/tech/regulatory/resource","compare to company state","create actionable signal or ignore"]},
  {id:"experiment_loop",ownerAgent:"growth_agent",trigger:"approved hypothesis",consequence:"external",steps:["hypothesis","metric/guardrails","sample/segment","launch bounded experiment","measure","analyze","adopt/modify/kill","record learning"]},
  {id:"agent_evolution_loop",ownerAgent:"evolution_brain",trigger:"repeated workflow evidence or agent drift",consequence:"internal",steps:["identify gap","propose prompt/tool/skill/agent change","quarantine","tests/security/evals","shadow","bounded","promote or reject","monitor"]},
  {id:"coverage_audit_loop",ownerAgent:"coverage_auditor",trigger:"weekly + major external change",consequence:"internal",steps:["compare domain/agent/skill/tool coverage","scan GitHub/world","detect missing/obsolete/duplicated capability","build-buy-integrate-partner-remove analysis","create reviewed proposal"]},
  {id:"backup_restore_loop",ownerAgent:"backup_restore_agent",trigger:"scheduled",consequence:"external",steps:["verify backups","integrity check","isolated restore","application smoke","RPO/RTO evidence","alert/remediate failures"]},
  {id:"vendor_exit_loop",ownerAgent:"vendor_agent",trigger:"critical vendor concentration/renewal",consequence:"internal",steps:["dependency map","exportability","alternative providers","migration dry run","cost/risk comparison","exit readiness score"]},
  {id:"enterprise_value_review",ownerAgent:"enterprise_value_agent",trigger:"weekly/monthly/quarterly",consequence:"internal",steps:["activation/retention","growth/revenue quality","margin/economics","distribution","moat","concentration","trust","org/capital","identify value-destroying constraints"]},
] as const;
