import Link from "next/link";
import { StatusDot } from "@/components/brand";
import { requireViewer } from "@/lib/auth";
import { loadWorkspaceSummary } from "@/lib/data";
import { FREE_BETA_LIMITS } from "@/lib/product-limits";

export default async function SettingsPage() {
  const viewer = await requireViewer("/app/settings");
  const workspace = await loadWorkspaceSummary(viewer);
  return <main className="workspace"><div className="workspace-heading"><div><span className="eyebrow">Workspace control</span><h1>Settings</h1><p>Organization, access, integrations, exports, and account boundaries for {viewer.email}.</p></div><Link className="button button--outline" href="/app/onboarding">Revisit onboarding</Link></div><div className="settings-grid">
    <section className="panel"><span className="eyebrow">Organization</span><h2>{workspace?.organizationName || "Complete onboarding"}</h2><dl className="settings-list"><div><dt>Domain</dt><dd>{workspace?.website || "Not yet set"}</dd></div><div><dt>Category</dt><dd>{workspace?.category || "Not yet set"}</dd></div><div><dt>Workspace status</dt><dd>{viewer.mode === "demo" ? "Preview data" : "Customer workspace"}</dd></div></dl></section>
    <section className="panel"><span className="eyebrow">AI collection</span><h2>Connection status</h2><div className="integration-list"><div><span><StatusDot tone="gray" /><strong>Live AI provider</strong></span><small>Activate a server-side provider connection before collection begins.</small></div><div><span><StatusDot tone="gray" /><strong>Background collection</strong></span><small>Activate a production job connection before scheduled runs begin.</small></div><div><span><StatusDot tone={viewer.mode === "demo" ? "yellow" : "green"} /><strong>Workspace data</strong></span><small>{viewer.mode === "demo" ? "Preview records" : "Supabase-backed workspace"}</small></div></div></section>
    <section className="panel"><span className="eyebrow">Team and permissions</span><h2>Workspace owner</h2><div className="member-row"><span>{viewer.name.slice(0,1).toUpperCase()}</span><div><strong>{viewer.name}</strong><small>Owner &middot; {viewer.email}</small></div><b>Full access</b></div><p className="table-caption">Invite teammates as your workspace plan and permissions are activated.</p></section>
    <section className="panel"><span className="eyebrow">Data controls</span><h2>Export or close</h2><p>Exports include prompt, run, source, opportunity, placement, and evidence records. Production deletion follows the signed retention policy.</p><div className="settings-actions"><a className="button button--outline" href="/api/export/source-map">Export Source Map &darr;</a><span className="danger-button is-disabled">Deletion requires owner re-authentication</span></div></section>
    <section className="panel panel--wide" id="integration-access"><span className="eyebrow">Plan capacity</span><h2>Visible, enforceable usage controls.</h2><p>{FREE_BETA_LIMITS.buyerQuestions} approved buyer questions, {FREE_BETA_LIMITS.runUnitsPerMonth} provider-prompt observations per month, {FREE_BETA_LIMITS.historyDays} days of history, and one workspace owner. Capacity changes only through verified entitlement and usage controls.</p><ol className="access-steps"><li>Keep model credentials in the server secret manager, never in the database.</li><li>Use only the exact provider and model that the workspace has approved.</li><li>Record every prompt, model, time, answer, and citation.</li><li>Show failed or partial collection instead of filling gaps with estimates.</li></ol></section>
    <section className="panel" id="evidence-import"><span className="eyebrow">Evidence intake</span><h2>Prepare verified claims</h2><p>Live evidence needs a project, item owner, source URL or approved file, usage rights, verification date, limitations, and expiry date.</p></section>
  </div></main>;
}
