import Link from "next/link";
import { Arrow, StatusDot } from "@/components/brand";
import { demoCompany, engineCoverage } from "@/lib/demo-data";
import { requireViewer } from "@/lib/auth";
import { loadPlacements, loadRuns, loadSourceMap } from "@/lib/data";

export default async function DashboardPage() {
  const viewer = await requireViewer("/app");
  const [runs, sources, placements] = await Promise.all([loadRuns(viewer), loadSourceMap(viewer), loadPlacements(viewer)]);
  const latest = runs[0] || { presence: 0, firstMention: 0, answers: 0 };
  const published = placements.filter(p => ["published","indexed","first cited","repeatedly cited"].includes(p.stage)).length;
  return <main className="workspace"><div className="workspace-heading"><div><span className="eyebrow">{viewer.mode === "demo" ? demoCompany.category : "Live organization"}</span><h1>Here is what the sources say.</h1><p>{viewer.mode === "demo" ? `Evidence window: ${demoCompany.window}. ` : ""}No outcome is inferred beyond the recorded run.</p></div><Link className="button button--ink" href="/app/source-map">Open Source Map <Arrow /></Link></div><div className="metric-grid"><article><span>Brand presence</span><strong>{latest.presence}%</strong><small>{runs.length ? `Across ${latest.answers} answers` : "No completed runs"}</small></article><article><span>First-mention share</span><strong>{latest.firstMention}%</strong><small>{runs.length ? "Latest recorded run" : "No completed runs"}</small></article><article><span>Deciding sources</span><strong>{sources.length}</strong><small>{sources.filter(s => s.clientPresent).length} currently name you</small></article><article><span>Tracked actions</span><strong>{placements.length}</strong><small>{published} published or beyond</small></article></div><div className="dashboard-grid"><section className="panel panel--wide"><div className="panel-heading"><div><span className="eyebrow">Engine coverage</span><h2>{viewer.mode === "demo" ? "Presence is uneven by engine." : "Review coverage by provider."}</h2></div><Link href="/app/runs">Run evidence →</Link></div>{viewer.mode === "demo" ? <div className="engine-list">{engineCoverage.map((row) => <div key={row.engine}><span>{row.engine}</span><div className="bar"><i style={{width: `${row.presence}%`}} /></div><strong>{row.presence}%</strong><small>+{row.delta}</small></div>)}</div> : <div className="empty-state empty-state--compact"><p>Per-provider coverage appears after reviewed live answers are aggregated.</p></div>}</section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Priority sources</span><h2>Where the gap is actionable.</h2></div></div>{sources.length ? <div className="compact-sources">{sources.filter(s => !s.clientPresent).slice(0,4).map(s => <Link href="/app/source-map" key={s.id}><span><StatusDot tone={s.feasibility === "high" ? "green" : "yellow"} /><strong>{s.domain}</strong></span><small>{s.route}</small></Link>)}</div> : <div className="empty-state empty-state--compact"><p>No mapped sources yet.</p></div>}</section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Pipeline</span><h2>Action state, not promises.</h2></div></div><div className="stage-summary">{["identified","pitched","published","first cited"].map(stage => <div key={stage}><strong>{placements.filter(p => p.stage === stage).length}</strong><span>{stage}</span></div>)}</div><Link className="text-link" href="/app/placements">Open the action tracker <Arrow /></Link></section></div></main>;
}
