import type { Metadata } from "next";
import Link from "next/link";
import { Arrow } from "@/components/brand";
import { PublicShell } from "@/components/public-shell";

export const metadata: Metadata = { title: "About", description: "Why Foremention exists and how it is being built." };

export default function AboutPage() {
  return <PublicShell><section className="page-hero"><div className="shell narrow-heading"><span className="eyebrow">About Foremention</span><h1>Be the first mention.</h1><p>When an AI system builds a shortlist, buyers often see a recommendation before they visit a vendor website. Foremention exists to show what shaped that answer—and whether the evidence is stable enough to act on.</p></div></section><section className="section section--paper"><div className="shell about-grid"><div><span className="eyebrow">Built platform-first</span><h2>Self-serve software is the operating model.</h2><p>Customers connect a brand, define buyer questions, run evidence collection, review exact sources, inspect recommendation reliability, and track action over time. The product keeps evidence, judgments, and limitations visible instead of hiding them behind one score.</p></div><div className="about-ledger"><span>Current operating truth</span><dl><div><dt>Lead product</dt><dd>Recommendation intelligence platform</dd></div><div><dt>Core system</dt><dd>Source Map, evidence history, and Decision Lab</dd></div><div><dt>Primary buyer</dt><dd>Lean B2B SaaS growth teams</dd></div><div><dt>Promise</dt><dd>Traceable collection, review, and decision support</dd></div><div><dt>Not promised</dt><dd>Publisher acceptance, AI rankings, or revenue</dd></div></dl></div></div></section><section className="section section--ink"><div className="shell split-section"><div><span className="eyebrow eyebrow--on-ink">Operating principles</span><h2>Evidence before theatre.</h2></div><div className="truth-list"><div><span>01</span><p><strong>No invented authority.</strong> No fake customer logos, reviews, team size, or case-study results.</p></div><div><span>02</span><p><strong>No manipulative placement.</strong> No sockpuppets, undisclosed promotion, fabricated reviews, or link schemes.</p></div><div><span>03</span><p><strong>No magical attribution.</strong> Actions, observed change, and business contribution are reported separately.</p></div></div></div></section><section className="cta-band"><div className="shell cta-band__inner"><div><span className="eyebrow">See the method</span><h2>Every claim should have a trail.</h2></div><Link className="button button--ink button--large" href="/methodology">Read the methodology <Arrow /></Link></div></section></PublicShell>;
}
