import type { Metadata } from "next";
import Link from "next/link";
import { Arrow } from "@/components/brand";
import { PublicShell } from "@/components/public-shell";

export const metadata: Metadata = { title: "About", description: "Why Foremention exists and how it is being built." };

export default function AboutPage() {
  return <PublicShell><section className="page-hero"><div className="shell narrow-heading"><span className="eyebrow">About Foremention</span><h1>Be the first mention.</h1><p>In an AI-generated shortlist, one company becomes the reference the answer points back to. Foremention exists to show what shaped that position and give teams the infrastructure to compete with evidence.</p></div></section><section className="section section--paper"><div className="shell about-grid"><div><span className="eyebrow">Built platform-first</span><h2>Self-serve software is the operating model.</h2><p>Customers connect a brand, define buyer questions, run evidence collection, inspect exact sources, and track change inside the product. Every verified observation strengthens the Recommendation Graph while evidence and limitations remain visible.</p></div><div className="about-ledger"><span>Current operating truth</span><dl><div><dt>Lead product</dt><dd>Recommendation intelligence platform</dd></div><div><dt>Core infrastructure</dt><dd>The Recommendation Graph and Source Map</dd></div><div><dt>Primary buyer</dt><dd>Lean B2B SaaS teams</dd></div><div><dt>Promise</dt><dd>Traceable collection, analysis, and monitoring</dd></div><div><dt>Not promised</dt><dd>Publisher acceptance or AI rankings</dd></div></dl></div></div></section><section className="section section--ink"><div className="shell split-section"><div><span className="eyebrow eyebrow--on-ink">Operating principles</span><h2>Evidence before theatre.</h2></div><div className="truth-list"><div><span>01</span><p><strong>No invented authority.</strong> No fake customer logos, reviews, team size, or case-study results.</p></div><div><span>02</span><p><strong>No manipulative placement.</strong> No sockpuppets, undisclosed promotion, fabricated reviews, or link schemes.</p></div><div><span>03</span><p><strong>No magical attribution.</strong> Actions, observed change, and business contribution are reported separately.</p></div></div></div></section><section className="cta-band"><div className="shell cta-band__inner"><div><span className="eyebrow">See the method</span><h2>Every claim should have a trail.</h2></div><Link className="button button--ink button--large" href="/methodology">Read the methodology <Arrow /></Link></div></section></PublicShell>;
}
