import type { Metadata } from "next";
import Link from "next/link";
import { Arrow } from "@/components/brand";
import { PublicShell } from "@/components/public-shell";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({ title: "About Foremention", description: "Why Foremention is building customer-operated recommendation intelligence for AI answer visibility, exact sources, evidence reliability, and measured change.", path: "/about" });

export default function AboutPage() {
  return <PublicShell><section className="page-hero"><div className="shell narrow-heading"><span className="eyebrow">About Foremention</span><h1>Be the first mention.</h1><p>When an AI system builds a shortlist, the answer can shape what a buyer investigates next. Foremention exists to show what appeared, which sources were returned with it, and whether the evidence is strong enough to act on.</p></div></section><section className="section section--paper"><div className="shell about-grid"><div><span className="eyebrow">Why Foremention</span><h2>AI visibility needs an audit trail.</h2><p>A useful answer is more than a visibility score. Teams should be able to trace an observation back to the buyer question, provider result, returned citations, review state, and collection date—then compare the same approved question later without turning correlation into causation.</p></div><div className="about-ledger"><span>What the product is built to show</span><dl><div><dt>What you monitor</dt><dd>Buyer questions and the AI answers collected for them</dd></div><div><dt>What you inspect</dt><dd>Returned citation URLs and the evidence recorded from reviewed pages</dd></div><div><dt>What you compare</dt><dd>Repeated observations for the same approved question when they are genuinely comparable</dd></div><div><dt>What stays separate</dt><dd>Provider output, Foremention inference, and human review</dd></div><div><dt>What we do not promise</dt><dd>Rankings, citations, publisher acceptance, traffic, leads, revenue, or causation</dd></div></dl></div></div></section><section className="section section--ink"><div className="shell split-section"><div><span className="eyebrow eyebrow--on-ink">Operating principles</span><h2>Evidence before theatre.</h2></div><div className="truth-list"><div><span>01</span><p><strong>No invented authority.</strong> No fake customer logos, reviews, team size, or case-study results.</p></div><div><span>02</span><p><strong>No manipulative placement.</strong> No sockpuppets, undisclosed promotion, fabricated reviews, or link schemes.</p></div><div><span>03</span><p><strong>No magical attribution.</strong> Actions, observed change, and business contribution are reported separately.</p></div></div></div></section><section className="cta-band"><div className="shell cta-band__inner"><div><span className="eyebrow">See the method</span><h2>Every claim should have a trail.</h2></div><Link className="button button--ink button--large" href="/methodology">Read the methodology <Arrow /></Link></div></section></PublicShell>;
}
