import Link from "next/link";
import { Arrow } from "@/components/brand";
import { requireViewer } from "@/lib/auth";
import { loadSourceMap } from "@/lib/data";

const influence = { high: 90, medium: 68, emerging: 44 };
const feasibility = { high: 90, medium: 62, low: 28 };

export default async function OpportunitiesPage() { const viewer = await requireViewer("/app/opportunities"); const entries = await loadSourceMap(viewer); const rows = entries.filter(source => !source.clientPresent).map(source => ({...source, score: Math.round(influence[source.influence] * .6 + feasibility[source.feasibility] * .4)})).sort((a,b) => b.score-a.score); return <main className="workspace"><div className="workspace-heading"><div><span className="eyebrow">Ranked action layer</span><h1>Source opportunities</h1><p>Observed influence and product-assessed feasibility remain separate inputs to a transparent priority score.</p></div><Link className="button button--ink" href="/app/placements">Open action pipeline <Arrow /></Link></div><section className="panel panel--flush">{rows.length ? <div className="opportunity-list">{rows.map((source,index) => <article key={source.id}><div className="opportunity-score"><span>Priority</span><strong>{source.score}</strong><small>/100</small></div><div><span className="opportunity-rank">#{index+1} · {source.type}</span><h2>{source.domain}</h2><p>{source.title}</p><div className="opportunity-meta"><span>{source.evidenceCount} observations</span><span>{source.influence} influence</span><span>{source.feasibility} feasibility</span><span>{source.route}</span></div></div><Link href={`/app/sources/${source.id}`} aria-label={`Open source record for ${source.domain}`}>Open record <Arrow /></Link></article>)}</div> : <div className="empty-state"><h2>No ranked opportunities yet.</h2><p>Complete onboarding and collect a reviewed run before Foremention ranks source opportunities.</p></div>}</section></main>; }
