import type { Metadata } from "next";
import { PublicShell } from "@/components/public-shell";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  title: "Privacy",
  description: "How Foremention collects, uses, protects, retains, and removes account, workspace, integration, public-source, analytics, and support data.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return <PublicShell>
    <section className="page-hero"><div className="shell narrow-heading"><span className="eyebrow">Effective July 27, 2026</span><h1>Privacy</h1><p>This notice explains the product data Foremention processes, why it is needed, and the choices available to account owners.</p></div></section>
    <article className="legal-copy shell">
      <div className="legal-summary"><strong>Plain-language summary</strong><p>Foremention uses account and workspace data to operate the product. It does not sell personal information. A live integration is used only after it is connected, and customer metrics do not appear from fictional data.</p></div>
      <h2>Information you provide</h2>
      <p>This may include account details, company and category information, buyer questions, competitor names, evidence records, source reviews, action notes, integration configuration, billing contact information, and support communications.</p>
      <h2>Information generated by the product</h2>
      <p>When requested and technically connected, Foremention may record AI-provider responses, visible provider and model labels, citations, public webpage details, review states, source maps, reliability checks, product activity, and timestamps. Demo workspaces are labelled and kept separate from customer records.</p>
      <h2>How information is used</h2>
      <p>Data is used to authenticate users, operate customer-requested collection, maintain evidence history, generate workspace recommendations, secure and troubleshoot the service, provide support, enforce plan capacity, and improve product reliability.</p>
      <h2>Service providers and integrations</h2>
      <p>Foremention may rely on infrastructure, database, email, analytics, error-monitoring, payment, and AI providers. A feature that requires a provider or customer integration remains labelled until that connection is active. Providers process data under their own terms as applicable.</p>
      <h2>Website measurement</h2>
      <p>Foremention may use PostHog EU for limited product and web analytics. The integration is configured without session replay, automatic click or form capture, form values, AI-provider answers, citations, or customer evidence. It records page routes and selected product milestones so Foremention can find broken journeys and improve the product. Identified product events use internal account and organization IDs rather than names or email addresses. Google Analytics and Google Tag Manager are not loaded.</p>
      <h2>Public-source research</h2>
      <p>Foremention can record public AI answers and public webpages as dated observations. Public availability does not remove access controls, contractual restrictions, robots directives, intellectual-property rights, or reasonable request limits.</p>
      <h2>Security and access</h2>
      <p>Foremention is designed around role-based workspace access, encrypted transport, server-side secret handling, and row-level data controls. No service can guarantee absolute security; account owners should use strong credentials and grant integrations only the minimum required access.</p>
      <h2>Retention and deletion</h2>
      <p>Data is kept while an account is active and as needed for security, legal, billing, backup, and operational obligations. Retention may vary by plan and data type. Account owners may request export or deletion, subject to applicable obligations and documented backup cycles.</p>
      <h2>Your choices</h2>
      <p>Subject to applicable law and contractual requirements, account owners may request access, correction, export, restriction, or deletion. They may also disconnect integrations and opt out of non-essential communications.</p>
      <h2>Contact</h2>
      <p>Send privacy questions or requests to <a href="mailto:hello@foremention.com">hello@foremention.com</a>. We may ask for reasonable verification before fulfilling an account-data request.</p>
      <h2>Changes to this notice</h2>
      <p>Material changes will be reflected by a revised effective date and, when appropriate, an in-product or email notice.</p>
    </article>
  </PublicShell>;
}
