"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function AuthForm({ mode, next = "/app" }: { mode: "login" | "signup"; next?: string }) {
  const router = useRouter(); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  async function submit(formData: FormData) { setBusy(true); setError(""); try { const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(formData.entries())) }); const data = (await response.json()) as { error?: string; message?: string; session?: boolean }; if (!response.ok) { setError(data.error || "We could not complete that request. Check your details and try again."); setBusy(false); return; } if (data.session === false) { setError(data.message || "Check your email to confirm your account."); setBusy(false); return; } router.push(next.startsWith("/") ? next : "/app"); router.refresh(); } catch { setError("The connection failed. Please try again."); setBusy(false); } }
  return <div className="auth-card"><div><span className="eyebrow">{mode === "login" ? "Workspace access" : "Create your workspace"}</span><h1>{mode === "login" ? "Sign in to Foremention." : "Start your recommendation intelligence workspace."}</h1><p>{mode === "login" ? "Your buyer questions, answer runs, Source Map, evidence, and analytics live in one secure workspace." : "Bring your category into one place: buyer questions, answer evidence, source pages, competitors, and movement over time."}</p></div><form action={submit}>{mode === "signup" && <label>Full name<input name="full_name" required autoComplete="name" /></label>}<label>Work email<input type="email" name="email" required autoComplete="email" /></label><label>Password<input type="password" name="password" required minLength={8} autoComplete={mode === "login" ? "current-password" : "new-password"} /><small>Use at least 8 characters.</small></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button--ink button--wide" type="submit" disabled={busy}>{busy ? "Working..." : mode === "login" ? "Sign in" : "Create workspace"}</button></form><p className="auth-switch">{mode === "login" ? <>No account? <Link href="/signup">Create a workspace</Link></> : <>Already have an account? <Link href="/login">Sign in</Link></>}</p></div>;
}
