"use client";
import { useEffect, useState } from "react";
type Status = { configured: boolean; connected: boolean; parentPageId?: string; workspaceName?: string };
export function NotionSettings({ demo }: { demo: boolean }) {
  const [status, setStatus] = useState<Status>({ configured: false, connected: false }); const [page, setPage] = useState(""); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!demo) void fetch("/api/integrations/notion").then((r) => r.json()).then((v) => { if (v.data) { setStatus(v.data); setPage(v.data.parentPageId || ""); } }).catch(() => setMessage("Notion status could not be loaded.")); }, [demo]);
  async function connect() { setBusy("connect"); try { const r = await fetch("/api/integrations/notion/connect", { method: "POST" }); const v = await r.json(); if (!r.ok || !v.data?.authorizationUrl) throw new Error(v.error || "Notion could not be connected."); window.location.assign(v.data.authorizationUrl); } catch (e) { setMessage(e instanceof Error ? e.message : "Notion could not be connected."); setBusy(""); } }
  async function save() { setBusy("save"); try { const r = await fetch("/api/integrations/notion", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ parentPageId: page }) }); const v = await r.json(); if (!r.ok) throw new Error(v.error || "The Notion export page could not be saved."); setMessage("Notion export page saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "The Notion export page could not be saved."); } finally { setBusy(""); } }
  async function exportNow() { setBusy("export"); try { const r = await fetch("/api/integrations/notion/export", { method: "POST" }); const v = await r.json(); if (!r.ok) throw new Error(v.error || "The digest could not be exported."); setMessage("A dated Source Map digest was created in Notion."); } catch (e) { setMessage(e instanceof Error ? e.message : "The digest could not be exported."); } finally { setBusy(""); } }
  return <div className="integration-connector"><p>Export the weekly Source Map digest to a Notion page shared with Foremention. Only recorded workspace results are included.</p>{status.connected ? <><label>Shared parent page ID<input value={page} onChange={(e) => setPage(e.target.value)} placeholder="Notion page ID" /></label><div className="settings-actions"><button className="button button--outline" disabled={Boolean(busy)} onClick={() => void save()}>{busy === "save" ? "Saving…" : "Save page"}</button><button className="button button--outline" disabled={Boolean(busy) || !status.parentPageId && !page} onClick={() => void exportNow()}>{busy === "export" ? "Exporting…" : "Export digest"}</button></div></> : <button className="button button--outline" disabled={demo || busy === "connect" || !status.configured} onClick={() => void connect()}>{busy === "connect" ? "Opening Notion…" : "Connect Notion"}</button>}<small>{demo ? "Connections are disabled in the fictional demo." : status.connected ? `Connected${status.workspaceName ? ` to ${status.workspaceName}` : ""}.` : status.configured ? "Ready to authorize." : "Unavailable until Notion OAuth is configured."}</small>{message && <p className="inline-notice" role="status">{message}</p>}</div>;
}
