"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";

type Result = { id: string; brand: string; category: string; score: number; appearedIn: number; questions: Array<{ question: string; appeared: boolean }>; citations: string[]; provider: string; model: string; observedAt: string; methodology: string };

export function VisibilityScoreForm({ initialId = "" }: { initialId?: string }) {
  const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(Boolean(initialId)); const [message, setMessage] = useState(""); const lock = useRef(false);
  useEffect(() => { if (!initialId) return; void fetch(`/api/public/score?id=${encodeURIComponent(initialId)}`).then((r) => r.json().then((v) => ({ r, v }))).then(({ r, v }) => { if (!r.ok) throw new Error(v.error || "The shared score is unavailable."); setResult(v.data); }).catch((e) => setMessage(e instanceof Error ? e.message : "The shared score is unavailable.")).finally(() => setBusy(false)); }, [initialId]);
  async function submit(formData: FormData) { if (lock.current) return; lock.current = true; setBusy(true); setMessage(""); setResult(null); try { const response = await fetch("/api/public/score", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ brand: formData.get("brand"), category: formData.get("category") }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "The live score could not be completed."); setResult(body.data); window.history.replaceState({}, "", `/score?id=${encodeURIComponent(body.data.id)}`); } catch (e) { setMessage(e instanceof Error ? e.message : "The live score could not be completed."); } finally { lock.current = false; setBusy(false); } }
  async function share() { if (!result) return; const url = `${window.location.origin}/score?id=${result.id}`; try { await navigator.clipboard.writeText(url); setMessage("Share link copied. The dated result expires after seven days."); } catch { setMessage(url); } }
  return <div className="score-tool"><form className="intake-form" action={submit} aria-busy={busy}><label>Brand name<input name="brand" minLength={2} maxLength={80} required placeholder="Foremention" /></label><label>Category buyers use<input name="category" minLength={3} maxLength={160} required placeholder="AI recommendation intelligence for B2B SaaS" /></label><button className="button button--ink button--large" type="submit" disabled={busy}>{busy ? "Running five live checks…" : "Calculate live score →"}</button><p className="form-fineprint">Three checks per day. One provider, one dated collection, no ranking guarantee.</p></form>{message && <p className={result ? "inline-notice" : "form-error"} role="status">{message}</p>}{result && <section className="panel score-result"><span className="eyebrow">Dated provider observation</span><h2>{result.brand}: {result.score}/100</h2><p>The brand appeared in {result.appearedIn} of 5 answers returned by {result.provider} using {result.model} on {new Date(result.observedAt).toLocaleDateString()}.</p><div className="team-list">{result.questions.map((item) => <article key={item.question}><div><span>{item.appeared ? "✓" : "—"}</span><div><strong>{item.question}</strong><small>{item.appeared ? "Brand appeared in the answer" : "Brand did not appear in the answer"}</small></div></div></article>)}</div><p className="table-caption">{result.methodology}</p><div className="settings-actions"><button className="button button--outline" type="button" onClick={() => void share()}>Copy share link</button><Link className="button button--ink" href="/signup">Monitor your category</Link></div></section>}</div>;
}
