import type { Placement, SourceMapEntry, VisibilityRun } from "@/lib/types";

export const demoCompany = {
  name: "Northstar HR",
  category: "HR software for distributed teams",
  domain: "northstarhr.example",
  window: "Last 30 days",
};

export const sourceMapEntries: SourceMapEntry[] = [
  {
    id: "src-01",
    rank: 1,
    domain: "remoteworklab.com",
    title: "The 12 best HR platforms for distributed teams",
    url: "https://remoteworklab.com/guides/hr-platforms",
    type: "Editorial list",
    influence: "high",
    engines: ["ChatGPT", "Perplexity", "Google AI"],
    clientPresent: false,
    competitors: ["Deel", "Rippling", "HiBob"],
    crawlerAccess: "open",
    route: "editorial outreach",
    feasibility: "high",
    evidenceCount: 18,
  },
  {
    id: "src-02",
    rank: 2,
    domain: "peopleops.report",
    title: "2026 global people operations benchmark",
    url: "https://peopleops.report/benchmarks/2026",
    type: "Research report",
    influence: "high",
    engines: ["ChatGPT", "Claude", "Perplexity"],
    clientPresent: false,
    competitors: ["Deel", "Remote"],
    crawlerAccess: "open",
    route: "original research",
    feasibility: "medium",
    evidenceCount: 15,
  },
  {
    id: "src-03",
    rank: 3,
    domain: "stackbrief.com",
    title: "HRIS comparison: workflows, payroll, and compliance",
    url: "https://stackbrief.com/compare/hris",
    type: "Comparison",
    influence: "high",
    engines: ["ChatGPT", "Perplexity"],
    clientPresent: true,
    competitors: ["Rippling", "Gusto", "BambooHR"],
    crawlerAccess: "open",
    route: "comparison inclusion",
    feasibility: "high",
    evidenceCount: 12,
  },
  {
    id: "src-04",
    rank: 4,
    domain: "hrleaders.community",
    title: "What HR system works for a 200-person remote team?",
    url: "https://hrleaders.community/t/remote-hris-200",
    type: "Community thread",
    influence: "medium",
    engines: ["Perplexity", "Google AI"],
    clientPresent: false,
    competitors: ["HiBob", "BambooHR"],
    crawlerAccess: "open",
    route: "community participation",
    feasibility: "medium",
    evidenceCount: 9,
  },
  {
    id: "src-05",
    rank: 5,
    domain: "worktechreview.com",
    title: "Northstar HR review: a practical operator's view",
    url: "https://worktechreview.com/reviews/northstar-hr",
    type: "Product review",
    influence: "medium",
    engines: ["ChatGPT", "Claude"],
    clientPresent: true,
    competitors: ["Remote"],
    crawlerAccess: "partial",
    route: "legitimate review",
    feasibility: "high",
    evidenceCount: 8,
  },
  {
    id: "src-06",
    rank: 6,
    domain: "futureofpeople.org",
    title: "Expert panel: running people operations across borders",
    url: "https://futureofpeople.org/panels/global-people-ops",
    type: "Expert roundup",
    influence: "medium",
    engines: ["Claude", "Perplexity"],
    clientPresent: false,
    competitors: ["Deel"],
    crawlerAccess: "open",
    route: "expert contribution",
    feasibility: "medium",
    evidenceCount: 7,
  },
  {
    id: "src-07",
    rank: 7,
    domain: "saasbuyers.guide",
    title: "Best HR software for growing companies",
    url: "https://saasbuyers.guide/hr/growing-companies",
    type: "Buyer guide",
    influence: "emerging",
    engines: ["Google AI"],
    clientPresent: false,
    competitors: ["Gusto", "Rippling"],
    crawlerAccess: "blocked",
    route: "editorial outreach",
    feasibility: "low",
    evidenceCount: 4,
  },
  {
    id: "src-08",
    rank: 8,
    domain: "operatornotes.co",
    title: "The hidden cost of fragmented HR operations",
    url: "https://operatornotes.co/people/fragmented-hr",
    type: "Analysis",
    influence: "emerging",
    engines: ["ChatGPT"],
    clientPresent: false,
    competitors: ["HiBob"],
    crawlerAccess: "open",
    route: "original research",
    feasibility: "high",
    evidenceCount: 3,
  },
];

export const demoRuns: VisibilityRun[] = [
  { id: "RUN-2407", date: "Jul 20, 2026", status: "complete", prompts: 40, answers: 160, citations: 94, presence: 31, firstMention: 12, newSources: 4 },
  { id: "RUN-2307", date: "Jul 13, 2026", status: "complete", prompts: 40, answers: 160, citations: 88, presence: 28, firstMention: 10, newSources: 2 },
  { id: "RUN-2207", date: "Jul 06, 2026", status: "complete", prompts: 36, answers: 144, citations: 81, presence: 24, firstMention: 9, newSources: 3 },
  { id: "RUN-2107", date: "Jun 29, 2026", status: "review", prompts: 36, answers: 142, citations: 77, presence: 22, firstMention: 8, newSources: 1 },
];

export const demoPlacements: Placement[] = [
  { id: "PL-101", source: "remoteworklab.com", page: "Best HR platforms", route: "editorial outreach", owner: "Maya", stage: "pitched", updated: "2h ago", promptImpact: 9 },
  { id: "PL-102", source: "peopleops.report", page: "2026 benchmark", route: "original research", owner: "Ari", stage: "qualified", updated: "Yesterday", promptImpact: 7 },
  { id: "PL-103", source: "stackbrief.com", page: "HRIS comparison", route: "comparison inclusion", owner: "Maya", stage: "repeatedly cited", updated: "Jul 19", promptImpact: 12 },
  { id: "PL-104", source: "worktechreview.com", page: "Northstar HR review", route: "legitimate review", owner: "Ari", stage: "first cited", updated: "Jul 18", promptImpact: 6 },
  { id: "PL-105", source: "futureofpeople.org", page: "Expert panel", route: "expert contribution", owner: "Maya", stage: "accepted", updated: "Jul 17", promptImpact: 5 },
  { id: "PL-106", source: "hrleaders.community", page: "Remote HRIS thread", route: "community participation", owner: "Ari", stage: "published", updated: "Jul 15", promptImpact: 4 },
  { id: "PL-107", source: "operatornotes.co", page: "Fragmented HR ops", route: "original research", owner: "Maya", stage: "identified", updated: "Jul 14", promptImpact: 3 },
];

export const engineCoverage = [
  { engine: "ChatGPT", presence: 38, citations: 31, delta: 6 },
  { engine: "Perplexity", presence: 44, citations: 28, delta: 4 },
  { engine: "Claude", presence: 21, citations: 17, delta: 2 },
  { engine: "Google AI", presence: 19, citations: 18, delta: 1 },
];
