import Link from "next/link";
import { requireViewer } from "@/lib/auth";
import { loadQuestionPerformance, loadRunAnswers, loadRuns, loadSourceMap } from "@/lib/data";

export default async function AnalyticsPage() {
  const viewer = await requireViewer("/app/analytics");
  const [allRuns, sources, questions] = await Promise.all([loadRuns(viewer), loadSourceMap(viewer), loadQuestionPerformance(viewer)]);
  const runs = allRuns.filter((run) => ["review", "complete", "partial"].includes(run.status)).reverse();
  if (!runs.length) {
    const pendingOrFailed = allRuns.find((run) => ["queued", "running", "failed"].includes(run.status));
    return <main className="workspace"><div className="workspace-heading"><div><span className="eyebrow">Observed performance</span><h1>Recommendation analytics</h1><p>Analytics begin only after a provider returns persisted observations.</p></div></div><section className="panel empty-state empty-state--border"><h2>{pendingOrFailed?.status === "failed" ? "Your audit is taking longer than expected — we'll notify you when it's ready." : pendingOrFailed ? "Your first audit is still running." : "No observed baseline exists yet."}</h2><p>{pendingOrFailed?.status === "failed" ? "No zero-value placeholder is being presented as a result. Inspect the failed run and retry when the provider is available." : pendingOrFailed ? "This page will populate automatically when real answers and citations arrive." : "Start the first connected provider run. Foremention will never substitute demo values for customer data."}</p><Link className="button button--ink" href={pendingOrFailed ? `/app/runs/${pendingOrFailed.id}` : "/app/runs"}>Open Answer Runs →</Link></section></main>;
  }
  const latest = runs.at(-1)!; const answers = await loadRunAnswers(viewer, latest.id);
  const isReviewed = latest.status === "complete" || latest.status === "partial"; const earliest = runs[0];
  const recurringSources = sources.filter((source) => source.evidenceCount > 1).length;
  const reviewedSourceCount = sources.filter((source) => source.crawlerAccess !== "unknown").length;
  return <main className="workspace">
    <div className="workspace-heading"><div><span className="eyebrow">Observed performance</span><h1>Recommendation analytics</h1><p>Every value below comes from persisted provider observations. {isReviewed ? "The latest run passed human review." : "The first baseline is visible now and remains labelled unreviewed until a person approves it."} These values do not guarantee buyer behavior or revenue impact.</p></div></div>
    <div className="metric-grid"><article><span>Brand presence</span><strong>{latest.presence}%</strong><small>{runs.length > 1 ? `${latest.presence - earliest.presence >= 0 ? "+" : ""}${latest.presence - earliest.presence} points vs first observed run` : isReviewed ? "Current reviewed baseline" : "Current unreviewed baseline"}</small></article><article><span>First-mention share</span><strong>{latest.firstMention}%</strong><small>Latest observed run</small></article><article><span>Citation observations</span><strong>{latest.citations}</strong><small>{recurringSources} recurring mapped sources</small></article><article><span>Observed runs</span><strong>{runs.length}</strong><small>{runs.length > 1 ? `${runs.reduce((sum, run) => sum + run.answers, 0)} persisted answers` : "A second comparable run is needed for trend"}</small></article></div>
    <div className="analytics-grid"><section className="panel panel--wide"><span className="eyebrow">{runs.length > 1 ? "Brand presence" : "Current baseline"}</span><h2>{runs.length > 1 ? "Approved collection trend" : answers[0]?.prompt || "First approved collection"}</h2>{runs.length > 1 ? <div className="trend-chart trend-chart--dynamic" style={{ gridTemplateColumns: `repeat(${Math.min(runs.length, 12)}, minmax(46px, 1fr))` }} role="img" aria-label={`Brand presence across ${runs.length} approved runs`}>{runs.slice(-12).map((run, index) => <div key={run.id}><i style={{ height: `${Math.max(2, run.presence)}%` }} /><span>R{Math.max(1, runs.length - 11) + index}</span><small>{run.presence}%</small></div>)}</div> : <div className="baseline-record"><strong>{answers[0]?.provider}{answers[0]?.model ? ` · ${answers[0].model}` : ""}</strong><p>{answers[0] ? `${answers[0].citations.length} cited sources were preserved from this verified answer. Run the same question again before interpreting movement.` : "The reviewed run establishes a baseline. A second comparable collection is required before Foremention draws a trend."}</p></div>}<p className="table-caption">Run IDs, provider responses, dates, and citations remain available in Answer Runs and the Evidence Vault.</p></section><section className="panel"><span className="eyebrow">Source review progress</span><h2>{reviewedSourceCount} of {sources.length} pages checked.</h2><div className="empty-state empty-state--compact"><p>{sources.length ? `${sources.length - reviewedSourceCount} cited pages still need page-level verification before they become confirmed opportunities.` : "No Source Map is available yet."}</p><Link className="text-link" href="/app/source-map">Review mapped sources →</Link></div></section></div>
    <section className="panel panel--flush question-performance"><div className="panel-heading panel-heading--padded"><div><span className="eyebrow">Question performance</span><h2>Keep the questions that produce inspectable evidence.</h2><p>Ranked by citations and exact brand mentions in human-verified answers. This is evidence yield, not search volume or revenue value.</p></div></div>{questions.length ? <div className="question-performance__table"><div className="question-performance__row question-performance__head"><span>Buyer question</span><span>Runs</span><span>Citations</span><span>Cited answers</span><span>Brand mentions</span><span>Guidance</span></div>{questions.map((question) => <div className="question-performance__row" key={question.key}><strong>{question.question}</strong><span>{question.runCount}</span><span>{question.citationCount}</span><span>{question.citedAnswerPct}%</span><span>{question.brandMentionCount}</span><span>{question.guidance}</span></div>)}</div> : <div className="empty-state"><h2>No verified question results yet.</h2><p>Review the first completed run to compare evidence yield by buyer question.</p></div>}</section>
  </main>;
}
