import Link from "next/link";
import { requireViewer } from "@/lib/auth";
import { loadChangeGraph } from "@/lib/change-graph";
import { loadQuestionPerformance, loadRunAnswers, loadRuns, loadSourceMap } from "@/lib/data";
import { productStateLabel, stateForRun } from "@/lib/product-state";

const signed = (value: number) => `${value > 0 ? "+" : ""}${value}`;
const changeKindLabel = (kind: string) => ({
  methodology: "Methodology",
  brand_mention: "Brand mention",
  citation: "Citation",
  source: "Source",
  source_content: "Page observation",
  competitor: "Competitor context",
  context: "AI answer context",
}[kind] || "Observed change");

export default async function AnalyticsPage() {
  const viewer = await requireViewer("/app/analytics");
  const [allRuns, sources, questions] = await Promise.all([loadRuns(viewer), loadSourceMap(viewer), loadQuestionPerformance(viewer)]);
  const runs = allRuns.filter((run) => ["review", "complete", "partial"].includes(run.status)).reverse();
  if (!runs.length) {
    const pendingOrFailed = allRuns.find((run) => ["queued", "running", "failed"].includes(run.status));
    const state = stateForRun(pendingOrFailed ? { status: pendingOrFailed.status, answerCount: pendingOrFailed.answers, citationCount: pendingOrFailed.citations } : null);
    return <main className="workspace" data-product-state={state}><div className="workspace-heading"><div><span className="eyebrow">Did anything change?</span><h1>Analytics</h1><p>Analytics begin only after a provider returns persisted observations. Foremention will never substitute demo values for customer data.</p><p className="table-caption"><strong>{productStateLabel(state)}</strong></p></div></div><section className="panel empty-state empty-state--border"><h2>{pendingOrFailed?.status === "failed" ? "The latest collection needs another try." : pendingOrFailed ? "Your first collection is still running." : "No observed baseline exists yet."}</h2><p>{pendingOrFailed?.status === "failed" ? "Your audit is taking longer than expected or ended before a reviewed baseline was ready. No zero-value placeholder is being presented as a result. Inspect the failed collection and retry when the AI system is available." : pendingOrFailed ? "This page will populate automatically when real answers and citations arrive." : "Start the first connected AI collection. Foremention will never substitute demo values for customer data."}</p><Link className="button button--ink" href={pendingOrFailed ? `/app/runs/${pendingOrFailed.id}` : "/app/runs"}>Open AI Results →</Link></section></main>;
  }

  const latest = runs.at(-1)!;
  const previous = runs.length > 1 ? runs.at(-2)! : null;
  const [answers, changeGraph] = await Promise.all([
    loadRunAnswers(viewer, latest.id),
    loadChangeGraph(viewer, latest.id, previous?.id || null),
  ]);
  const comparable = changeGraph.status === "comparable";
  const isReviewed = latest.status === "complete" || latest.status === "partial";
  const recurringSources = sources.filter((source) => source.evidenceCount > 1).length;
  const reviewedSourceCount = sources.filter((source) => source.crawlerAccess !== "unknown").length;
  const recentRuns = runs.slice(-8).reverse();
  const state = latest.status === "review" ? "NEEDS_REVIEW" : runs.length > 1 ? "COMPLETE" : "PARTIALLY_COMPLETE";

  return <main className="workspace" data-product-state={state}>
    <div className="workspace-heading"><div><span className="eyebrow">Did anything change?</span><h1>Analytics</h1><p>Compare dated collections, question evidence yield, and source-review progress. Every number comes from persisted provider observations; movement is observed change, not proof that an action caused it.</p><p className="table-caption"><strong>{runs.length > 1 ? `${runs.length} observed collections` : "Current reviewed baseline"}</strong> · Latest {latest.date} · {latest.answers} answer{latest.answers === 1 ? "" : "s"}</p></div><Link className="button button--outline" href="/app/runs">Inspect AI Results</Link></div>

    <div className="metric-grid"><article><span>Brand presence</span><strong>{latest.presence}%</strong><small>{latest.answers} answer{latest.answers === 1 ? "" : "s"} in latest collection{previous ? comparable ? ` · ${signed(latest.presence - previous.presence)} pts vs comparable previous` : " · cross-collection movement withheld" : isReviewed ? " · Current reviewed baseline" : " · Current unreviewed baseline"}</small></article><article><span>First mention</span><strong>{latest.firstMention}%</strong><small>{latest.answers} answer{latest.answers === 1 ? "" : "s"}{previous ? comparable ? ` · ${signed(latest.firstMention - previous.firstMention)} pts vs comparable previous` : " · cross-collection movement withheld" : " · baseline only"}</small></article><article><span>Citation observations</span><strong>{latest.citations}</strong><small>{previous ? comparable ? `${signed(latest.citations - previous.citations)} vs comparable previous` : "Cross-collection movement withheld" : `${recurringSources} recurring mapped sources`}</small></article><article><span>Reviewed sources</span><strong>{reviewedSourceCount} of {sources.length}</strong><small>{sources.length - reviewedSourceCount} cited page{sources.length - reviewedSourceCount === 1 ? "" : "s"} still need review</small></article></div>

    <section className="panel panel--flush"><div className="panel-heading panel-heading--padded"><div><span className="eyebrow">Change Graph</span><h2>{changeGraph.status === "comparable" ? "Latest movement passed the comparability gate." : changeGraph.status === "not_comparable" ? "Latest cross-collection movement is withheld." : changeGraph.status === "fictional" ? "Change Graph is disabled in the fictional demo." : "One collection establishes the baseline."}</h2><p>{changeGraph.note}</p></div><Link className="text-link" href={`/app/runs/${latest.id}`}>Inspect latest evidence →</Link></div>{changeGraph.events.length ? <div className="notification-list">{changeGraph.events.map((event) => <article key={event.id}><div><span>{changeKindLabel(event.kind)} · {event.direction.replaceAll("_", " ")}</span><strong>{event.title}</strong><p>{event.detail}</p></div><Link href={event.href}>Inspect →</Link></article>)}</div> : <div className="empty-state"><h2>{changeGraph.status === "comparable" ? "No material movement was recorded in the supported change types." : "No comparable movement is available yet."}</h2><p>Foremention keeps brand mentions, citations, unique sources, cited-page changes, competitor context, and exact answer text separate instead of collapsing them into one score.</p></div>}<p className="table-caption">Comparability requires the same reviewed buyer-question, provider, exact-model, and methodology matrix. Saved page changes compare a cited page with its own previous bounded fingerprint and do not prove causation.</p></section>

    <div className="analytics-grid"><section className="panel panel--wide"><span className="eyebrow">Brand presence over time</span><h2>{runs.length > 1 ? comparable ? "Latest pair is methodologically comparable" : "Observed collection history · latest movement withheld" : "One collection establishes a baseline"}</h2>{runs.length > 1 ? <div className="trend-chart trend-chart--dynamic" style={{ gridTemplateColumns: `repeat(${Math.min(runs.length, 12)}, minmax(46px, 1fr))` }} role="img" aria-label={`Brand presence across ${runs.length} observed collections`}>{runs.slice(-12).map((run, index) => <div key={run.id}><i style={{ height: `${Math.max(2, run.presence)}%` }} /><span>R{Math.max(1, runs.length - 11) + index}</span><small>{run.presence}%</small></div>)}</div> : <div className="baseline-record"><strong>{answers[0]?.provider}{answers[0]?.model ? ` · ${answers[0].model}` : ""}</strong><p>{answers[0] ? `${answers[0].citations.length} cited source${answers[0].citations.length === 1 ? "" : "s"} were preserved from this answer. Repeat the same methodology before interpreting movement.` : "The reviewed run establishes a baseline. A second comparable collection is required before Foremention draws a trend."}</p></div>}<p className="table-caption">Bars show persisted collection observations, not automatically comparable trend points. Only a pair that passes the Change Graph gate should be interpreted as movement. Exact provider, model, date, answer, and citations remain inspectable in AI Results.</p></section><section className="panel"><span className="eyebrow">Source review progress</span><h2>{reviewedSourceCount} of {sources.length} pages checked.</h2><div className="empty-state empty-state--compact"><p>{sources.length ? `${sources.length - reviewedSourceCount} cited pages still need page-level verification before they become reviewed opportunities.` : "No cited sources are available yet."}</p><Link className="text-link" href="/app/source-map">Review Sources →</Link></div></section></div>

    <section className="panel panel--flush"><div className="panel-heading panel-heading--padded"><div><span className="eyebrow">Recent collections</span><h2>See the denominator behind every trend.</h2><p>Latest first. A status of Needs review is kept separate from reviewed history.</p></div></div><div className="run-table"><div className="run-row run-row--head"><span>Date</span><span>Status</span><span>Answers</span><span>Citations</span><span>Brand presence</span><span>First mention</span><span>New sources</span><span>Inspect</span></div>{recentRuns.map((run) => <Link className="run-row" href={`/app/runs/${run.id}`} key={run.id}><strong>{run.date}</strong><span>{productStateLabel(stateForRun({ status: run.status, answerCount: run.answers, citationCount: run.citations }))}</span><strong>{run.answers}</strong><strong>{run.citations}</strong><span>{run.presence}% of {run.answers}</span><span>{run.firstMention}% of {run.answers}</span><strong>{run.newSources}</strong><span>Open →</span></Link>)}</div></section>

    <section className="panel panel--flush question-performance"><div className="panel-heading panel-heading--padded"><div><span className="eyebrow">Question performance</span><h2>Which buyer questions produce inspectable evidence?</h2><p>Based on citations and exact brand mentions in human-verified answers. This is evidence yield, not search volume or revenue value. It does not estimate demand.</p></div></div>{questions.length ? <div className="question-performance__table"><div className="question-performance__row question-performance__head"><span>Buyer question</span><span>Reviewed runs</span><span>Citations</span><span>Cited answer rate</span><span>Brand mentions</span><span>Guidance</span></div>{questions.map((question) => <div className="question-performance__row" key={question.key}><strong>{question.question}</strong><span>{question.runCount}</span><span>{question.citationCount}</span><span>{question.citedAnswerPct}% across {question.runCount}</span><span>{question.brandMentionCount}</span><span>{question.guidance}</span></div>)}</div> : <div className="empty-state"><h2>No verified question results yet.</h2><p>Review the first completed collection to compare evidence yield by buyer question.</p></div>}</section>
  </main>;
}
